#!/usr/bin/env python3
"""Generate synthetic fixtures + sidecars across all Certificates categories.

Covers:

  - `x509/synthetic/` — Ed25519 self-signed, ECDSA P-256, ECDSA P-384,
    RSA-2048, SHA-1-signed RSA, non-self-signed (intermediate signed by
    CA), DER re-encoding of one fixture
  - `crls/synthetic/` — empty CRL, small CRL with revocations, SHA-1
    signed CRL
  - `ssh/synthetic/` — rsa-4096, ed25519, ecdsa-nistp256, ecdsa-nistp384
    public keys; OpenSSH CA-signed user cert and host cert (cross-
    algorithm)
  - `pgp/synthetic/` — v4 RSA and v4 Ed25519 armored public keys
  - `private-keys/synthetic/` — unencrypted PKCS#8 RSA / Ed25519;
    OpenSSH unencrypted RSA-4096 / Ed25519; encrypted PKCS#8 AES-256
    PBKDF2; encrypted PKCS#8 scrypt; OpenSSH-encrypted Ed25519;
    legacy PEM encrypted RSA
  - `keystores/synthetic/` — JKS, JCEKS, PKCS#12 (unencrypted +
    encrypted)
  - `pem-bundles/synthetic/` — small 2-cert chain
  - `edge-cases/` — truncated, corrupt, empty, whitespace-only,
    blank-lines, typo-header, wrong-magic variants, plain-text

Each fixture is paired with a sidecar computed from the generated
bytes where ground truth can be derived (X.509), or a hand-written
sidecar for non-X.509 fixtures whose ground truth the Certificates
strategy will produce in Phase 4-7.

## Discipline

- The script is idempotent — re-running overwrites existing fixtures.
- Private-key fixtures that land in the repo carry the banner
  `# GOAT RODEO TEST KEY - NOT A SECRET - DO NOT USE ANYWHERE ELSE`
  per the policy in `test_data/certificates/private-keys/SOURCES.md`.
- Transient private keys used only to synthesize other artifacts
  (e.g., the test CA that signs intermediate certs) are generated
  in a tmp dir and deleted before exit.

## Invariant compliance

- Invariant #13: the script needs openssl, ssh-keygen, gpg, keytool,
  and Python's `cryptography` library. The Docker image at
  `test_data/certificates/tools/Dockerfile` ships all of these.
"""

from __future__ import annotations

import hashlib
import os
import random
import shutil
import subprocess
import sys
import tempfile
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

# Phase 0 plan: "If the generation requires randomness, the script
# sets a pinned seed." We pin Python-level entropy here. Note that
# external tools (ssh-keygen, gpg, keytool, openssl genpkey) do NOT
# respect this seed and continue to use OS entropy — see ADR-002 for
# the determinism gradient and the "committed bytes are canonical"
# policy that closes the gap for non-seedable tools.
PINNED_SEED = 0x60_47_47_47_47_47_47_47  # "GOAT" in repeated hex
random.seed(PINNED_SEED)

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cert_sidecar  # noqa: E402

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import (
    ed25519,
    ec,
    rsa,
)
from cryptography.x509.oid import NameOID

CORPUS_ROOT = Path(__file__).resolve().parents[1]
TODAY = date.today().isoformat()
TEST_BANNER = (
    "# GOAT RODEO TEST KEY - NOT A SECRET - DO NOT USE ANYWHERE ELSE\n"
)
SOURCE_GENERATED = "generated by test_data/certificates/tools/bootstrap_synthetic.py"


def _sh(cmd: list[str], *, cwd: str | None = None, input_bytes: bytes | None = None) -> bytes:
    """Run a command, capture stdout, raise on nonzero."""
    r = subprocess.run(
        cmd, cwd=cwd, input=input_bytes, check=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE,
    )
    return r.stdout


def _write(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)


def _write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _append(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(text)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


# --- shared helpers ---

def _make_x509_selfsigned(
    key, subject_cn: str, not_before: datetime, not_after: datetime,
    is_ca: bool = True,
    sig_hash: hashes.HashAlgorithm | None = hashes.SHA256(),
) -> x509.Certificate:
    """Return a self-signed certificate with the given key + metadata."""
    name = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, subject_cn),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Goat Rodeo Test"),
        x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
    ])
    builder = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(not_before)
        .not_valid_after(not_after)
    )
    if is_ca:
        builder = builder.add_extension(
            x509.BasicConstraints(ca=True, path_length=None), critical=True
        ).add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
    # Ed25519 / Ed448 don't accept a hash algorithm argument
    from cryptography.hazmat.primitives.asymmetric import ed25519 as _ed25519
    from cryptography.hazmat.primitives.asymmetric import ed448 as _ed448
    if isinstance(key, (_ed25519.Ed25519PrivateKey, _ed448.Ed448PrivateKey)):
        return builder.sign(key, None)
    return builder.sign(key, sig_hash)


def _make_x509_intermediate(
    subject_cn: str,
    issuer_key, issuer_cert: x509.Certificate,
    not_before: datetime, not_after: datetime,
    sig_hash: hashes.HashAlgorithm = hashes.SHA256(),
):
    """Return an intermediate cert signed by `issuer_key`."""
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, subject_cn),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Goat Rodeo Test"),
        x509.NameAttribute(NameOID.COUNTRY_NAME, "US"),
    ])
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(issuer_cert.subject)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(not_before)
        .not_valid_after(not_after)
        .add_extension(x509.BasicConstraints(ca=True, path_length=0), critical=True)
        .sign(issuer_key, sig_hash)
    )
    return key, cert


def _write_cert_fixture(
    dir_: Path, stem: str, cert: x509.Certificate,
    *, description: str, source: str, der: bool = False
) -> None:
    if der:
        data = cert.public_bytes(serialization.Encoding.DER)
        ext = "der"
        mime_types = ["application/pkix-cert"]
    else:
        data = cert.public_bytes(serialization.Encoding.PEM)
        ext = "pem"
        mime_types = ["application/x-pem-file", "application/x-x509-ca-cert"]
    fixture_path = dir_ / f"{stem}.{ext}"
    _write(fixture_path, data)
    # Compute sidecar from DER bytes
    der_bytes = cert.public_bytes(serialization.Encoding.DER)
    sc = cert_sidecar.x509_sidecar(
        der_bytes, description=description, source=source,
        retrieved_at=TODAY, mime_types=mime_types,
    )
    cert_sidecar.write_sidecar(str(dir_ / f"{stem}.{ext}.expected.json"), sc)


# --- subcategory generators ---

def gen_x509_synthetic() -> list[str]:
    """Produce synthetic X.509 fixtures. Returns SOURCES.md row strings."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "x509" / "synthetic"

    # 1. Ed25519 self-signed (the canonical alg=ed25519 coverage fixture)
    now = datetime(2026, 1, 1, tzinfo=timezone.utc)
    ed_key = ed25519.Ed25519PrivateKey.generate()
    ed_cert = _make_x509_selfsigned(
        ed_key, "GoatRodeo Test Ed25519", now, now + timedelta(days=3650),
    )
    _write_cert_fixture(
        dir_, "ed25519-selfsigned", ed_cert,
        description="Goat Rodeo synthetic Ed25519 self-signed CA",
        source=SOURCE_GENERATED,
    )
    sha = _sha256(ed_cert.public_bytes(serialization.Encoding.PEM))
    rows.append(f"| synthetic/ed25519-selfsigned.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # DER re-encoding of the same cert — covers the DER-encoding coverage cell
    _write_cert_fixture(
        dir_, "ed25519-selfsigned-der", ed_cert,
        description="Goat Rodeo synthetic Ed25519 self-signed CA (DER)",
        source=SOURCE_GENERATED, der=True,
    )
    sha = _sha256(ed_cert.public_bytes(serialization.Encoding.DER))
    rows.append(f"| synthetic/ed25519-selfsigned-der.der | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # 2. ECDSA P-256 self-signed
    ec256_key = ec.generate_private_key(ec.SECP256R1())
    ec256_cert = _make_x509_selfsigned(
        ec256_key, "GoatRodeo Test EC P-256", now, now + timedelta(days=3650),
        sig_hash=hashes.SHA256(),
    )
    _write_cert_fixture(
        dir_, "ec-p256-selfsigned", ec256_cert,
        description="Goat Rodeo synthetic ECDSA P-256 self-signed",
        source=SOURCE_GENERATED,
    )
    sha = _sha256(ec256_cert.public_bytes(serialization.Encoding.PEM))
    rows.append(f"| synthetic/ec-p256-selfsigned.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # 3. ECDSA P-384 self-signed
    ec384_key = ec.generate_private_key(ec.SECP384R1())
    ec384_cert = _make_x509_selfsigned(
        ec384_key, "GoatRodeo Test EC P-384", now, now + timedelta(days=3650),
        sig_hash=hashes.SHA384(),
    )
    _write_cert_fixture(
        dir_, "ec-p384-selfsigned", ec384_cert,
        description="Goat Rodeo synthetic ECDSA P-384 self-signed",
        source=SOURCE_GENERATED,
    )
    sha = _sha256(ec384_cert.public_bytes(serialization.Encoding.PEM))
    rows.append(f"| synthetic/ec-p384-selfsigned.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # 4. RSA-2048 self-signed (small size; Mozilla has 4096 mostly)
    rsa2048_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    rsa2048_cert = _make_x509_selfsigned(
        rsa2048_key, "GoatRodeo Test RSA-2048", now, now + timedelta(days=3650),
    )
    _write_cert_fixture(
        dir_, "rsa-2048-selfsigned", rsa2048_cert,
        description="Goat Rodeo synthetic RSA-2048 self-signed",
        source=SOURCE_GENERATED,
    )
    sha = _sha256(rsa2048_cert.public_bytes(serialization.Encoding.PEM))
    rows.append(f"| synthetic/rsa-2048-selfsigned.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # 5. SHA-1 signed RSA (for deprecated-algo coverage).
    # The `cryptography` library refuses to sign with SHA-1 for safety;
    # we use the openssl CLI instead, which still permits it.
    with tempfile.TemporaryDirectory() as td:
        k = os.path.join(td, "sha1.key")
        c = os.path.join(td, "sha1.pem")
        _sh(["openssl", "genpkey", "-algorithm", "RSA",
             "-pkeyopt", "rsa_keygen_bits:2048", "-out", k])
        _sh(["openssl", "req", "-new", "-x509", "-key", k,
             "-subj", "/CN=GoatRodeo Test SHA1-legacy/O=Goat Rodeo Test/C=US",
             "-days", "3650",
             "-sha1",
             "-out", c])
        sha1_pem_bytes = Path(c).read_bytes()
        sha1_cert = x509.load_pem_x509_certificate(sha1_pem_bytes)
    _write_cert_fixture(
        dir_, "rsa-2048-sha1-selfsigned", sha1_cert,
        description="Goat Rodeo synthetic RSA-2048 SHA-1-signed (deprecated)",
        source=SOURCE_GENERATED,
    )
    sha = _sha256(sha1_cert.public_bytes(serialization.Encoding.PEM))
    rows.append(f"| synthetic/rsa-2048-sha1-selfsigned.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # 6. Non-self-signed intermediate (signed by rsa2048_cert)
    int_key, int_cert = _make_x509_intermediate(
        "GoatRodeo Test Intermediate CA",
        rsa2048_key, rsa2048_cert,
        now, now + timedelta(days=1825),
    )
    _write_cert_fixture(
        dir_, "rsa-2048-intermediate", int_cert,
        description="Goat Rodeo synthetic intermediate signed by RSA-2048 root",
        source=SOURCE_GENERATED,
    )
    sha = _sha256(int_cert.public_bytes(serialization.Encoding.PEM))
    rows.append(f"| synthetic/rsa-2048-intermediate.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{sha} |")

    # Also produce a small PEM bundle containing root + intermediate
    bundle_dir = CORPUS_ROOT / "pem-bundles" / "synthetic"
    bundle_pem = (
        rsa2048_cert.public_bytes(serialization.Encoding.PEM)
        + int_cert.public_bytes(serialization.Encoding.PEM)
    )
    _write(bundle_dir / "goatrodeo-test-chain.pem", bundle_pem)
    sha_bundle = _sha256(bundle_pem)
    # Sidecar for the bundle — two certs; pURLs deferred to Phase 4
    bundle_sidecar = {
        "description": "Goat Rodeo synthetic 2-cert PEM chain (RSA-2048 root + intermediate)",
        "source": SOURCE_GENERATED,
        "retrievedAt": TODAY,
        "itemCount": 1,
        "mimeTypes": {
            "mustContain": ["application/x-pem-file", "application/x-pem-bundle"]
        },
        "purls": {
            "mustContain": [
                "<computed: 2 spki + 2 cert pURLs in Phase 4>"
            ]
        },
        "metadata": {
            "mustContain": {
                "Certificates:KeystoreType": "pem-bundle",
                "Certificates:EntryCount": "2",
                "Certificates:CertCount": "2",
                "Certificates:KeyEntryCount": "0",
            }
        },
        "forbiddenMetadataKeys": [],
        "forbiddenMetadataPatterns": list(cert_sidecar.FORBIDDEN_PATTERNS_DEFAULT),
    }
    cert_sidecar.write_sidecar(
        str(bundle_dir / "goatrodeo-test-chain.pem.expected.json"),
        bundle_sidecar,
    )

    return rows + [
        f"| (pem-bundles/synthetic/goatrodeo-test-chain.pem) | {SOURCE_GENERATED} | {TODAY} | sha256:{sha_bundle} |"
    ]


def _hand_sidecar(
    dir_: Path, fixture_name: str,
    *,
    description: str, source: str, item_count: int = 1,
    mime_types: list[str], purls: list[str],
    mime_types_not: list[str] | None = None,
    purls_not: list[str] | None = None,
    metadata: dict[str, str] | None = None,
    forbidden_keys: list[str] | None = None,
) -> None:
    sc = {
        "description": description,
        "source": source,
        "retrievedAt": TODAY,
        "itemCount": item_count,
        "mimeTypes": {"mustContain": mime_types},
        "purls": {"mustContain": purls},
        "metadata": {"mustContain": metadata or {}},
        "forbiddenMetadataKeys": forbidden_keys or [],
        "forbiddenMetadataPatterns": list(cert_sidecar.FORBIDDEN_PATTERNS_DEFAULT),
    }
    if mime_types_not is not None:
        sc["mimeTypes"]["mustNotContain"] = mime_types_not
    if purls_not is not None:
        sc["purls"]["mustNotContain"] = purls_not
    cert_sidecar.write_sidecar(str(dir_ / f"{fixture_name}.expected.json"), sc)


def gen_ssh_synthetic() -> list[str]:
    """Generate SSH pubkeys and OpenSSH-cert fixtures."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "ssh" / "synthetic"
    dir_.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as td:
        variants = [
            ("rsa-4096", ["-t", "rsa", "-b", "4096"]),
            ("ed25519", ["-t", "ed25519"]),
            ("ecdsa-nistp256", ["-t", "ecdsa", "-b", "256"]),
            ("ecdsa-nistp384", ["-t", "ecdsa", "-b", "384"]),
        ]
        for name, args in variants:
            priv = os.path.join(td, f"id_{name}")
            _sh(["ssh-keygen", "-q", "-N", "", "-C", f"goatrodeo-{name}@test",
                 "-f", priv] + args)
            pub_bytes = Path(priv + ".pub").read_bytes()
            _write(dir_ / f"{name}-openssh.pub", pub_bytes)
            _hand_sidecar(
                dir_, f"{name}-openssh.pub",
                description=f"SSH public key ({name}) generated for testing",
                source=SOURCE_GENERATED,
                mime_types=["application/x-openssh-public-key"],
                purls=["<computed: pkg:ssh/sha256@... in Phase 5>"],
                metadata={"Certificates:KeyAlgorithm": "<computed in Phase 5>"},
            )
            rows.append(
                f"| synthetic/{name}-openssh.pub | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(pub_bytes)} |"
            )
            # Private key NOT committed — this is a pub-key fixture only.

        # OpenSSH CA setup
        ca_ed = os.path.join(td, "ca_ed25519")
        _sh(["ssh-keygen", "-q", "-N", "", "-C", "goatrodeo-ca",
             "-t", "ed25519", "-f", ca_ed])

        # User cert signed by Ed25519 CA, signing an Ed25519 user key
        user_key = os.path.join(td, "user_ed25519")
        _sh(["ssh-keygen", "-q", "-N", "", "-C", "goatrodeo-user",
             "-t", "ed25519", "-f", user_key])
        _sh(["ssh-keygen", "-s", ca_ed,
             "-I", "goatrodeo-test-user",
             "-n", "alice,bob",
             "-V", "+52w",
             f"{user_key}.pub"])
        _write(dir_ / "user-cert-ed25519.pub",
               Path(user_key + "-cert.pub").read_bytes())
        _hand_sidecar(
            dir_, "user-cert-ed25519.pub",
            description="OpenSSH user certificate (Ed25519 user key, Ed25519 CA)",
            source=SOURCE_GENERATED,
            mime_types=["application/x-openssh-certificate"],
            purls=["<computed: pkg:ssh/cert-sha256@... + pkg:ssh/sha256@... in Phase 5>"],
            metadata={
                "Certificates:SshCertType": "user",
                "Certificates:SshCertPrincipals": "alice,bob",
            },
        )
        rows.append(
            f"| synthetic/user-cert-ed25519.pub | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(Path(user_key + '-cert.pub').read_bytes())} |"
        )

        # Host cert: RSA-2048 host key signed by Ed25519 CA (cross-algorithm)
        host_key = os.path.join(td, "host_rsa")
        _sh(["ssh-keygen", "-q", "-N", "", "-C", "goatrodeo-host",
             "-t", "rsa", "-b", "2048", "-f", host_key])
        _sh(["ssh-keygen", "-s", ca_ed,
             "-I", "goatrodeo-test-host",
             "-h",
             "-n", "host1.example,host2.example",
             "-V", "+52w",
             f"{host_key}.pub"])
        _write(dir_ / "host-cert-rsa-signed-by-ed25519.pub",
               Path(host_key + "-cert.pub").read_bytes())
        _hand_sidecar(
            dir_, "host-cert-rsa-signed-by-ed25519.pub",
            description="OpenSSH host certificate — RSA-2048 key signed by Ed25519 CA (cross-algorithm)",
            source=SOURCE_GENERATED,
            mime_types=["application/x-openssh-certificate"],
            purls=["<computed in Phase 5>"],
            metadata={
                "Certificates:SshCertType": "host",
                "Certificates:SshCertPrincipals": "host1.example,host2.example",
            },
        )
        rows.append(
            f"| synthetic/host-cert-rsa-signed-by-ed25519.pub | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(Path(host_key + '-cert.pub').read_bytes())} |"
        )

    return rows


def gen_github_ssh() -> list[str]:
    """Download a handful of stable GitHub-hosted SSH pubkeys."""
    import urllib.request
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "ssh" / "github"
    dir_.mkdir(parents=True, exist_ok=True)
    # A small, stable set of maintainer accounts known to have public keys
    # that have been stable for years. If a URL 404s or returns empty, we
    # skip silently rather than fail the whole bootstrap.
    accounts = [
        "torvalds", "gvanrossum", "jepler", "dpp", "rcoh",
        "mitchellh", "ry", "pietroalbini", "dwrensha",
    ]
    for acct in accounts:
        url = f"https://github.com/{acct}.keys"
        try:
            with urllib.request.urlopen(url, timeout=10) as r:
                data = r.read()
        except Exception as e:
            print(f"  skip {url}: {e}", file=sys.stderr)
            continue
        if not data.strip():
            print(f"  skip {url}: empty body", file=sys.stderr)
            continue
        # Take only the first key per account to keep stems unique and to
        # avoid depending on a multi-key-per-account order we can't pin.
        first_line = data.splitlines()[0] + b"\n"
        if not first_line.startswith((
            b"ssh-rsa ", b"ssh-ed25519 ", b"ssh-dss ",
            b"ecdsa-sha2-nistp256 ", b"ecdsa-sha2-nistp384 ",
            b"ecdsa-sha2-nistp521 ",
        )):
            print(f"  skip {url}: unrecognized format", file=sys.stderr)
            continue
        fixture = dir_ / f"github-{acct}.pub"
        _write(fixture, first_line)
        _hand_sidecar(
            dir_, f"github-{acct}.pub",
            description=f"Real-world SSH public key — github.com/{acct}",
            source=url,
            mime_types=["application/x-openssh-public-key"],
            purls=["<computed in Phase 5>"],
            metadata={"Certificates:KeyAlgorithm": "<computed in Phase 5>"},
        )
        rows.append(
            f"| github/github-{acct}.pub | {url} | {TODAY} | sha256:{_sha256(first_line)} |"
        )
    return rows


def gen_pgp_synthetic() -> list[str]:
    """Generate v4 RSA and v4 Ed25519 PGP public keys via gpg."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "pgp" / "synthetic"
    dir_.mkdir(parents=True, exist_ok=True)

    for kind, algo_block in [
        ("rsa4096", "Key-Type: RSA\nKey-Length: 4096\nKey-Usage: cert,sign"),
        ("ed25519", "Key-Type: EDDSA\nKey-Curve: ed25519\nKey-Usage: cert,sign"),
    ]:
        with tempfile.TemporaryDirectory() as td:
            env = os.environ.copy()
            env["GNUPGHOME"] = td
            # Init gpg silently (creates trustdb etc.)
            subprocess.run(["gpg", "--homedir", td, "--batch", "--list-keys"],
                           check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            params = (
                "%no-protection\n"
                f"{algo_block}\n"
                f"Name-Real: GoatRodeo Test {kind}\n"
                f"Name-Email: goatrodeo-{kind}@test.invalid\n"
                "Expire-Date: 0\n"
                "%commit\n"
            )
            subprocess.run(
                ["gpg", "--homedir", td, "--batch", "--quiet",
                 "--gen-key"],
                input=params.encode(), check=True,
                stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            )
            # Export the armored public key
            r = subprocess.run(
                ["gpg", "--homedir", td, "--armor", "--export",
                 f"goatrodeo-{kind}@test.invalid"],
                check=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
            )
            pub = r.stdout
        fixture = dir_ / f"v4-{kind}-pub.asc"
        _write(fixture, pub)
        _hand_sidecar(
            dir_, f"v4-{kind}-pub.asc",
            description=f"PGP v4 {kind} public key (armored)",
            source=SOURCE_GENERATED,
            mime_types=["application/pgp-keys"],
            purls=["<computed: pkg:pgp/fingerprint@... in Phase 6>"],
            metadata={"Certificates:PgpKeyCount": "<computed in Phase 6>"},
        )
        rows.append(
            f"| synthetic/v4-{kind}-pub.asc | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(pub)} |"
        )
    return rows


def gen_private_keys() -> list[str]:
    """Unencrypted and encrypted private-key fixtures."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "private-keys" / "synthetic"
    dir_.mkdir(parents=True, exist_ok=True)
    banner = TEST_BANNER

    with tempfile.TemporaryDirectory() as td:
        # 1. PKCS#8 RSA-2048 unencrypted
        rsa_path = os.path.join(td, "rsa.pem")
        _sh(["openssl", "genpkey", "-algorithm", "RSA",
             "-pkeyopt", "rsa_keygen_bits:2048", "-out", rsa_path])
        rsa_pem = Path(rsa_path).read_bytes()
        # Prepend banner (must live above the BEGIN line for PEM — it is a
        # comment before any BEGIN block, allowed by the standard)
        fixture = dir_ / "pkcs8-rsa-2048-unencrypted.pem"
        _write(fixture, banner.encode() + rsa_pem)
        _hand_sidecar(
            dir_, "pkcs8-rsa-2048-unencrypted.pem",
            description="Unencrypted PKCS#8 RSA-2048 test key",
            source=SOURCE_GENERATED,
            mime_types=["application/x-pem-file", "application/x-pem-private-key"],
            purls=["<computed: derived pkg:x509/spki-sha256@... in Phase 7>"],
            metadata={
                "Certificates:Envelope": "plaintext",
                "Certificates:DerivedFromPrivateKey": "true",
                "Certificates:KeyAlgorithm": "rsa",
            },
        )
        rows.append(f"| synthetic/pkcs8-rsa-2048-unencrypted.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(banner.encode() + rsa_pem)} |")

        # 2. PKCS#8 Ed25519 unencrypted
        ed_path = os.path.join(td, "ed.pem")
        _sh(["openssl", "genpkey", "-algorithm", "ed25519", "-out", ed_path])
        ed_pem = Path(ed_path).read_bytes()
        fixture = dir_ / "pkcs8-ed25519-unencrypted.pem"
        _write(fixture, banner.encode() + ed_pem)
        _hand_sidecar(
            dir_, "pkcs8-ed25519-unencrypted.pem",
            description="Unencrypted PKCS#8 Ed25519 test key",
            source=SOURCE_GENERATED,
            mime_types=["application/x-pem-file", "application/x-pem-private-key"],
            purls=["<computed: pkg:x509/spki-sha256@...?alg=ed25519 in Phase 7>"],
            metadata={
                "Certificates:Envelope": "plaintext",
                "Certificates:DerivedFromPrivateKey": "true",
                "Certificates:KeyAlgorithm": "ed25519",
            },
        )
        rows.append(f"| synthetic/pkcs8-ed25519-unencrypted.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(banner.encode() + ed_pem)} |")

        # 3. OpenSSH Ed25519 unencrypted (ssh-keygen, no passphrase)
        ossh = os.path.join(td, "ossh_ed25519")
        _sh(["ssh-keygen", "-q", "-N", "", "-C", "goatrodeo-test",
             "-t", "ed25519", "-f", ossh])
        ossh_priv = Path(ossh).read_bytes()
        fixture = dir_ / "openssh-ed25519-unencrypted"
        _write(fixture, banner.encode() + ossh_priv)
        _hand_sidecar(
            dir_, "openssh-ed25519-unencrypted",
            description="Unencrypted OpenSSH Ed25519 private key",
            source=SOURCE_GENERATED,
            mime_types=["application/x-openssh-private-key"],
            purls=["<computed: pkg:ssh/sha256@... in Phase 7>"],
            metadata={
                "Certificates:Envelope": "plaintext",
                "Certificates:DerivedFromPrivateKey": "true",
                "Certificates:KeyAlgorithm": "ed25519",
            },
        )
        rows.append(f"| synthetic/openssh-ed25519-unencrypted | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(banner.encode() + ossh_priv)} |")

        # 4. OpenSSH RSA-4096 unencrypted
        ossh_rsa = os.path.join(td, "ossh_rsa")
        _sh(["ssh-keygen", "-q", "-N", "", "-C", "goatrodeo-test-rsa",
             "-t", "rsa", "-b", "4096", "-f", ossh_rsa])
        ossh_rsa_priv = Path(ossh_rsa).read_bytes()
        fixture = dir_ / "openssh-rsa-4096-unencrypted"
        _write(fixture, banner.encode() + ossh_rsa_priv)
        _hand_sidecar(
            dir_, "openssh-rsa-4096-unencrypted",
            description="Unencrypted OpenSSH RSA-4096 private key",
            source=SOURCE_GENERATED,
            mime_types=["application/x-openssh-private-key"],
            purls=["<computed in Phase 7>"],
            metadata={
                "Certificates:Envelope": "plaintext",
                "Certificates:KeyAlgorithm": "rsa",
            },
        )
        rows.append(f"| synthetic/openssh-rsa-4096-unencrypted | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(banner.encode() + ossh_rsa_priv)} |")

        # 5. PKCS#8 encrypted with AES-256 PBKDF2
        enc_pbkdf2 = os.path.join(td, "enc_pbkdf2.pem")
        _sh(["openssl", "pkcs8", "-topk8", "-v2", "aes-256-cbc",
             "-passout", "pass:GoatRodeoTestFixture",
             "-in", rsa_path, "-out", enc_pbkdf2])
        fixture = dir_ / "pkcs8-encrypted-aes256-pbkdf2.pem"
        _write(fixture, Path(enc_pbkdf2).read_bytes())
        _hand_sidecar(
            dir_, "pkcs8-encrypted-aes256-pbkdf2.pem",
            description="PKCS#8 encrypted private key (AES-256-CBC, PBKDF2)",
            source=SOURCE_GENERATED,
            mime_types=["application/x-pem-file", "application/x-pem-encrypted-private-key"],
            purls=[],  # Envelope path — no pURL
            purls_not=[
                "pkg:x509/spki-sha256@",  # pattern: any spki pURL absent
            ],
            metadata={
                "Certificates:Envelope": "pkcs8-encrypted",
                "Certificates:KdfAlgorithm": "pbkdf2",
            },
        )
        rows.append(f"| synthetic/pkcs8-encrypted-aes256-pbkdf2.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(Path(enc_pbkdf2).read_bytes())} |")

        # 6. PKCS#8 encrypted with scrypt (openssl 3.x only)
        enc_scrypt = os.path.join(td, "enc_scrypt.pem")
        try:
            _sh(["openssl", "pkcs8", "-topk8", "-scrypt",
                 "-passout", "pass:GoatRodeoTestFixture",
                 "-in", rsa_path, "-out", enc_scrypt])
            fixture = dir_ / "pkcs8-encrypted-scrypt.pem"
            _write(fixture, Path(enc_scrypt).read_bytes())
            _hand_sidecar(
                dir_, "pkcs8-encrypted-scrypt.pem",
                description="PKCS#8 encrypted private key (scrypt KDF)",
                source=SOURCE_GENERATED,
                mime_types=["application/x-pem-file", "application/x-pem-encrypted-private-key"],
                purls=[],
                metadata={
                    "Certificates:Envelope": "pkcs8-encrypted",
                    "Certificates:KdfAlgorithm": "scrypt",
                },
            )
            rows.append(f"| synthetic/pkcs8-encrypted-scrypt.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(Path(enc_scrypt).read_bytes())} |")
        except subprocess.CalledProcessError:
            print("  skip pkcs8-encrypted-scrypt — openssl does not support scrypt",
                  file=sys.stderr)

        # 7. OpenSSH encrypted Ed25519
        ossh_enc = os.path.join(td, "ossh_enc_ed25519")
        _sh(["ssh-keygen", "-q", "-N", "GoatRodeoTestFixture",
             "-C", "goatrodeo-test-enc",
             "-t", "ed25519", "-f", ossh_enc])
        fixture = dir_ / "openssh-encrypted-ed25519"
        _write(fixture, Path(ossh_enc).read_bytes())
        _hand_sidecar(
            dir_, "openssh-encrypted-ed25519",
            description="Encrypted OpenSSH Ed25519 private key (bcrypt KDF)",
            source=SOURCE_GENERATED,
            mime_types=["application/x-openssh-private-key"],
            purls=[],
            metadata={
                "Certificates:Envelope": "openssh-encrypted",
                "Certificates:KdfAlgorithm": "bcrypt",
            },
        )
        rows.append(f"| synthetic/openssh-encrypted-ed25519 | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(Path(ossh_enc).read_bytes())} |")

        # 8. Legacy PEM encrypted RSA (Proc-Type: 4,ENCRYPTED)
        legacy_enc = os.path.join(td, "legacy_enc.pem")
        _sh(["openssl", "rsa", "-aes256",
             "-passout", "pass:GoatRodeoTestFixture",
             "-in", rsa_path, "-out", legacy_enc,
             "-traditional"])
        fixture = dir_ / "pem-legacy-encrypted-rsa.pem"
        _write(fixture, Path(legacy_enc).read_bytes())
        _hand_sidecar(
            dir_, "pem-legacy-encrypted-rsa.pem",
            description="Legacy PEM-encrypted RSA private key (Proc-Type: 4,ENCRYPTED)",
            source=SOURCE_GENERATED,
            mime_types=["application/x-pem-file", "application/x-pem-private-key"],
            purls=[],
            metadata={
                "Certificates:Envelope": "pem-legacy-encrypted",
                "Certificates:Cipher": "aes-256-cbc",
            },
        )
        rows.append(f"| synthetic/pem-legacy-encrypted-rsa.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(Path(legacy_enc).read_bytes())} |")
    return rows


def gen_crls() -> list[str]:
    """Generate empty CRL, small CRL with revocations, SHA-1 CRL."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "crls" / "synthetic"
    dir_.mkdir(parents=True, exist_ok=True)

    from cryptography.x509 import ocsp  # noqa: F401  # confirm lib is present
    from cryptography.hazmat.primitives.asymmetric import padding  # noqa: F401

    now = datetime(2026, 1, 1, tzinfo=timezone.utc)

    def _build_crl(hash_alg, revoked: list[int]) -> tuple[bytes, bytes]:
        """Build a CRL signed by a fresh RSA-2048 CA. Returns (PEM, DER)."""
        ca_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
        ca = _make_x509_selfsigned(
            ca_key, "GoatRodeo Test CA (CRL signer)",
            now, now + timedelta(days=3650),
            sig_hash=hash_alg,
        )
        crl_builder = (
            x509.CertificateRevocationListBuilder()
            .issuer_name(ca.subject)
            .last_update(now)
            .next_update(now + timedelta(days=30))
        )
        for serial in revoked:
            rev = (
                x509.RevokedCertificateBuilder()
                .serial_number(serial)
                .revocation_date(now)
                .build()
            )
            crl_builder = crl_builder.add_revoked_certificate(rev)
        crl = crl_builder.sign(private_key=ca_key, algorithm=hash_alg)
        return (crl.public_bytes(serialization.Encoding.PEM),
                crl.public_bytes(serialization.Encoding.DER))

    # 1. Empty PEM CRL (sha256)
    pem, _ = _build_crl(hashes.SHA256(), [])
    _write(dir_ / "empty-crl.pem", pem)
    _hand_sidecar(
        dir_, "empty-crl.pem",
        description="Empty X.509 CRL (no revocations)",
        source=SOURCE_GENERATED,
        mime_types=["application/x-pem-file", "application/pkix-crl"],
        purls=["<computed: pkg:x509/crl-sha256@... in Phase 4>"],
        metadata={"Certificates:RevokedCount": "0"},
    )
    rows.append(f"| synthetic/empty-crl.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(pem)} |")

    # 2. Small CRL with 3 revocations (PEM)
    pem, _ = _build_crl(hashes.SHA256(), [0x1001, 0x1002, 0x1003])
    _write(dir_ / "small-crl.pem", pem)
    _hand_sidecar(
        dir_, "small-crl.pem",
        description="Small X.509 CRL with 3 revocations (SHA-256 signed)",
        source=SOURCE_GENERATED,
        mime_types=["application/x-pem-file", "application/pkix-crl"],
        purls=["<computed in Phase 4>"],
        metadata={"Certificates:RevokedCount": "3"},
    )
    rows.append(f"| synthetic/small-crl.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(pem)} |")

    # 3. SHA-1 signed CRL (deprecated).
    # Again, cryptography refuses SHA-1 signing; we shell out to openssl
    # ca -gencrl, which requires a minimal CA config.
    with tempfile.TemporaryDirectory() as td:
        ca_key = os.path.join(td, "ca.key")
        ca_pem = os.path.join(td, "ca.pem")
        _sh(["openssl", "genpkey", "-algorithm", "RSA",
             "-pkeyopt", "rsa_keygen_bits:2048", "-out", ca_key])
        _sh(["openssl", "req", "-new", "-x509", "-key", ca_key,
             "-subj", "/CN=GoatRodeo Test SHA1 CRL CA",
             "-days", "3650", "-sha1", "-out", ca_pem])
        # minimal openssl.cnf for gencrl
        cfg = os.path.join(td, "openssl.cnf")
        Path(cfg).write_text(f"""
[ca]
default_ca = CA_default
[CA_default]
dir = {td}
database = {td}/index.txt
new_certs_dir = {td}
serial = {td}/serial
crlnumber = {td}/crlnumber
default_md = sha1
default_crl_days = 30
policy = policy_any
certificate = {ca_pem}
private_key = {ca_key}
[policy_any]
commonName = supplied
""")
        Path(f"{td}/index.txt").write_text("")
        Path(f"{td}/serial").write_text("1000\n")
        Path(f"{td}/crlnumber").write_text("1000\n")
        crl_pem_path = os.path.join(td, "sha1-crl.pem")
        _sh(["openssl", "ca", "-gencrl", "-config", cfg, "-out", crl_pem_path,
             "-md", "sha1"])
        sha1_crl_bytes = Path(crl_pem_path).read_bytes()
    _write(dir_ / "sha1-crl.pem", sha1_crl_bytes)
    _hand_sidecar(
        dir_, "sha1-crl.pem",
        description="CRL signed with SHA-1 (deprecated algorithm)",
        source=SOURCE_GENERATED,
        mime_types=["application/x-pem-file", "application/pkix-crl"],
        purls=["<computed in Phase 4>"],
        metadata={"Certificates:SigAlgorithm": "sha1-rsa"},
    )
    rows.append(f"| synthetic/sha1-crl.pem | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(sha1_crl_bytes)} |")

    # 4. DER-encoded CRL (re-encoding of the small CRL)
    pem, der = _build_crl(hashes.SHA256(), [0x3001, 0x3002])
    _write(dir_ / "small-crl.der", der)
    _hand_sidecar(
        dir_, "small-crl.der",
        description="DER-encoded X.509 CRL (2 revocations)",
        source=SOURCE_GENERATED,
        mime_types=["application/pkix-crl"],
        purls=["<computed in Phase 4>"],
        metadata={"Certificates:RevokedCount": "2"},
    )
    rows.append(f"| synthetic/small-crl.der | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(der)} |")
    return rows


def gen_keystores() -> list[str]:
    """Generate JKS, JCEKS, PKCS#12 keystores via keytool."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "keystores" / "synthetic"
    dir_.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory() as td:
        for fmt, ext in [("JKS", "jks"), ("JCEKS", "jceks"), ("PKCS12", "p12")]:
            ks_path = os.path.join(td, f"ks.{ext}")
            # keytool requires >= 6-char password; we use a known one but
            # the strategy will try null first (for trust-only) and fall
            # back to treating as encrypted otherwise.
            _sh([
                "keytool", "-genkeypair",
                "-alias", "goatrodeo",
                "-dname", "CN=GoatRodeo Test,O=Goat Rodeo,C=US",
                "-keyalg", "RSA",
                "-keysize", "2048",
                "-validity", "3650",
                "-keystore", ks_path,
                "-storetype", fmt,
                "-storepass", "GoatRodeoTestFixture",
                "-keypass", "GoatRodeoTestFixture",
            ])
            data = Path(ks_path).read_bytes()
            fixture_name = f"encrypted-{ext}.{ext}"
            _write(dir_ / fixture_name, data)
            _hand_sidecar(
                dir_, fixture_name,
                description=f"Encrypted {fmt} keystore (password-protected; "
                            f"strategy null-password probe fails → envelope-only)",
                source=SOURCE_GENERATED,
                mime_types=[{
                    "JKS": "application/x-java-keystore",
                    "JCEKS": "application/x-java-jce-keystore",
                    "PKCS12": "application/pkcs12",
                }[fmt]],
                purls=[],
                metadata={
                    "Certificates:KeystoreType": {
                        "JKS": "jks", "JCEKS": "jceks", "PKCS12": "pkcs12",
                    }[fmt],
                    "Certificates:KeystoreEncrypted": "true",
                },
            )
            rows.append(f"| synthetic/{fixture_name} | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(data)} |")

        # Also: a null-password-readable JKS trust store (cert-only).
        # keytool -importcert with -noprompt and -storetype JKS with the
        # `-storepass ""` is rejected; modern keytool insists on a
        # password >= 6 chars. We still commit the above as "encrypted"
        # coverage and document the null-readable case as a Phase 4
        # follow-up — see docs/adrs/adr-001 follow-up.
        pass
    return rows


def gen_edge_cases() -> list[str]:
    """Generate edge-case / malformed fixtures for detector robustness."""
    rows: list[str] = []
    dir_ = CORPUS_ROOT / "edge-cases"
    # Note: edge-cases/ already exists from scaffold; don't overwrite SOURCES.md

    def _mk(name: str, data: bytes, descr: str,
            *, mime_types: list[str] | None = None,
            mime_types_not: list[str] | None = None):
        fixture = dir_ / name
        _write(fixture, data)
        _hand_sidecar(
            dir_, name,
            description=descr,
            source=SOURCE_GENERATED,
            mime_types=mime_types or [],
            purls=[],
            mime_types_not=mime_types_not,
            metadata={},
        )
        rows.append(f"| {name} | {SOURCE_GENERATED} | {TODAY} | sha256:{_sha256(data)} |")

    _mk("empty.pem", b"",
        "Empty file — detector must not claim anything",
        mime_types=[], mime_types_not=["application/pkix-cert"])
    _mk("whitespace-only.txt", b"   \n\t  \n\n  \n",
        "Whitespace-only file — detector must not claim anything",
        mime_types=[], mime_types_not=["application/pkix-cert"])
    _mk("plain-text.txt", b"This is just some plain text. No certificates here.\n",
        "Plain text file — detector must return currentMimes unchanged",
        mime_types=["text/plain"], mime_types_not=["application/pkix-cert"])
    _mk("pem-typo-header.pem",
        b"-----BEGIN CERTIFICAT-----\nAAAA\n-----END CERTIFICAT-----\n",
        "PEM file with typo in header — detector must NOT match",
        mime_types=[], mime_types_not=["application/pkix-cert", "application/x-x509-ca-cert"])
    _mk("truncated-pem.pem",
        b"-----BEGIN CERTIFICATE-----\nMIIFazCCA1OgAwIBAgIRAII" + b"QABC" * 5,
        "Valid BEGIN line followed by truncated base64 — Tika may still "
        "think this is PEM-shaped, but the strategy parser must fail to "
        "parse and decline to claim",
        mime_types=["application/x-pem-file"])
    _mk("wrong-magic-looks-like-jks.bin",
        b"\xfe\xed\xfe\xed garbage that is not actually a JKS keystore",
        "First 4 bytes match JKS magic but rest is garbage — detector "
        "may add the application/x-java-keystore MIME; Phase-4 parser "
        "must fail cleanly",
        mime_types=[])  # leave MIME-set loose; detector will add x-java-keystore
    _mk("der-prefix-not-x509.bin",
        b"\x30\x82\x00\x10" + b"\x00" * 18,
        "DER SEQUENCE prefix but neither a valid X.509 cert nor PKCS#12 — "
        "detector must not claim as pkix-cert",
        mime_types=[], mime_types_not=["application/pkix-cert"])
    _mk("pem-with-blank-lines.pem",
        b"-----BEGIN CERTIFICATE-----\n\n\nAAAA\n\n\n"
        b"-----END CERTIFICATE-----\n",
        "PEM file with extra blank lines — detector should still match "
        "but parser may reject base64 content; fixture documents the "
        "detector-vs-parser boundary",
        mime_types=["application/x-pem-file"])
    _mk("only-begin-marker.pem",
        b"-----BEGIN CERTIFICATE-----\n",
        "BEGIN marker with no END — detector may claim, parser will fail",
        mime_types=["application/x-pem-file"])
    _mk("random-noise.bin",
        os.urandom(1024),
        "1 KB of /dev/urandom — detector must not claim anything",
        mime_types=[])
    return rows


def main() -> int:
    """Run synthetic generators. Optional first argument restricts to one
    category — used by per-category `generate.sh` wrappers (see
    `test_data/certificates/{category}/synthetic/generate.sh`).
    """
    # Categories accepted as the optional first arg
    CATEGORY_ALIASES = {
        "x509": "x509",
        "ssh": "ssh",
        "pgp": "pgp",
        "crls": "crls",
        "keystores": "keystores",
        "private-keys": "private-keys",
        "edge-cases": "edge-cases",
        "pem-bundles": "pem-bundles",  # produced by gen_x509_synthetic
    }
    only = None
    if len(sys.argv) > 1:
        if sys.argv[1] not in CATEGORY_ALIASES:
            print(f"unknown category: {sys.argv[1]}; valid: "
                  f"{sorted(CATEGORY_ALIASES.keys())}", file=sys.stderr)
            return 2
        only = CATEGORY_ALIASES[sys.argv[1]]

    def _run_if(name: str, fn):
        if only is None or only == name:
            return fn()
        return []

    # Note: gen_x509_synthetic also produces a PEM-bundles fixture
    # (the synthetic 2-cert chain). When only="pem-bundles" we need the
    # x509 generator to run too.
    x509_rows = _run_if("x509", gen_x509_synthetic) if only != "pem-bundles" \
        else gen_x509_synthetic()
    ssh_rows = _run_if("ssh", gen_ssh_synthetic)
    github_rows = _run_if("ssh", gen_github_ssh)
    pgp_rows = _run_if("pgp", gen_pgp_synthetic)
    pk_rows = _run_if("private-keys", gen_private_keys)
    crl_rows = _run_if("crls", gen_crls)
    ks_rows = _run_if("keystores", gen_keystores)
    edge_rows = _run_if("edge-cases", gen_edge_cases)

    # Append rows into each SOURCES.md
    def _append_table(path: Path, header: str, rows: list[str]) -> None:
        if not rows:
            return
        _append(path, "\n" + header + "\n\n"
                "| Filename | Source | Retrieved | SHA-256 |\n"
                "|---|---|---|---|\n" + "\n".join(rows) + "\n")

    _append_table(CORPUS_ROOT / "x509" / "SOURCES.md",
                  "## Synthetic X.509 fixtures", x509_rows)
    _append_table(CORPUS_ROOT / "ssh" / "SOURCES.md",
                  "## Synthetic SSH fixtures", ssh_rows)
    _append_table(CORPUS_ROOT / "ssh" / "SOURCES.md",
                  "## GitHub .keys fixtures (real-world pubkeys)", github_rows)
    _append_table(CORPUS_ROOT / "pgp" / "SOURCES.md",
                  "## Synthetic PGP fixtures", pgp_rows)
    _append_table(CORPUS_ROOT / "private-keys" / "SOURCES.md",
                  "## Synthetic private-key fixtures", pk_rows)
    _append_table(CORPUS_ROOT / "crls" / "SOURCES.md",
                  "## Synthetic CRL fixtures", crl_rows)
    _append_table(CORPUS_ROOT / "keystores" / "SOURCES.md",
                  "## Synthetic keystore fixtures", ks_rows)
    _append_table(CORPUS_ROOT / "edge-cases" / "SOURCES.md",
                  "## Edge-case fixtures", edge_rows)

    total = (len(x509_rows) + len(ssh_rows) + len(github_rows)
             + len(pgp_rows) + len(pk_rows) + len(crl_rows)
             + len(ks_rows) + len(edge_rows))
    print(f"Wrote {total} synthetic fixtures across all categories",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
