/* Copyright 2026 David Pollak, Spice Labs, Inc. & Contributors
   Apache 2.0. */

package io.spicelabs.goatrodeo.omnibor.strategies

import org.json4s.*
import org.json4s.native.JsonMethods.*

/** Shared helper for loading metadata ground truth and parsing pURLs.
  *
  * The ground truth JSON files were generated by running a reference metadata
  * scanner against JARs in the test corpus. The files capture what the scanner
  * found for each JAR — pURLs with groupId/artifactId/version.
  *
  * Tests use this ground truth to verify Goat Rodeo finds at least as many
  * packages as the reference scanner. The scanner may use filename-derived
  * coordinates (which are often wrong), while Goat Rodeo uses companion POM
  * coordinates (which are correct). So the comparison is on artifactId superset
  * and pURL count, not exact pURL string matching.
  *
  * '''LLM context:''' This object provides:
  *   - `loadEntries` to read JSON ground truth files
  *   - `findEntry` to look up a JAR by name
  *   - `PurlParts` case class and parser for structured pURL comparison
  */
object MetadataGroundTruth {

  case class MetadataEntry(name: String, path: String, purls: List[String])

  /** Load metadata ground truth from a JSON resource file.
    *
    * The JSON format is an array of objects with `name`, `path`, and `purls`
    * fields — the same format as `metadata_multiple_purls.json`.
    */
  def loadEntries(resource: String): Vector[MetadataEntry] = {
    val is = getClass.getClassLoader.getResourceAsStream(resource)
    if (is == null) return Vector.empty

    val content =
      try {
        scala.io.Source.fromInputStream(is).mkString
      } finally is.close()

    val json = parse(content)

    json match {
      case JArray(arr) =>
        arr.map { entry =>
          val obj = entry.asInstanceOf[JObject].obj
          val name = obj
            .find(_._1 == "name")
            .map(_._2)
            .collect { case JString(s) => s }
            .getOrElse("")
          val path = obj
            .find(_._1 == "path")
            .map(_._2)
            .collect { case JString(s) => s }
            .getOrElse("")
          val purls = obj
            .find(_._1 == "purls")
            .map(_._2)
            .collect { case JArray(pa) =>
              pa.collect { case JString(s) => s }
            }
            .getOrElse(List.empty)
          MetadataEntry(name, path, purls)
        }.toVector
      case _ => Vector.empty
    }
  }

  /** Look up a JAR by name in the metadata entries. */
  def findEntry(
      entries: Vector[MetadataEntry],
      jarName: String
  ): Option[MetadataEntry] = {
    entries.find(_.name == jarName)
  }
}

/** Parsed components of a Maven pURL.
  *
  * A pURL like `pkg:maven/org.slf4j/slf4j-api@1.7.25?packaging=sources` parses
  * to:
  *   - groupId = "org.slf4j"
  *   - artifactId = "slf4j-api"
  *   - version = "1.7.25"
  *   - qualifiers = Map("packaging" -> "sources")
  *
  * '''Why this exists:''' Tests previously used
  * `.contains("packaging=sources")` to check for classifiers. This is fragile —
  * a malformed pURL like `pkg:maven/evil/packaging=sources@1` would pass.
  * Structured parsing is more robust.
  */
case class PurlParts(
    groupId: String,
    artifactId: String,
    version: String,
    qualifiers: Map[String, String]
)

object PurlParts {

  /** Parse a Maven pURL string into its components.
    *
    * Returns None if the string is not a valid Maven pURL.
    */
  def parse(purl: String): Option[PurlParts] = {
    if (!purl.startsWith("pkg:maven/")) return None

    val withoutPrefix = purl.substring("pkg:maven/".length)

    // Split off qualifiers (everything after ?)
    val qIdx = withoutPrefix.indexOf('?')
    val (pathVersion, qualifierStr) =
      if (qIdx >= 0)
        (withoutPrefix.substring(0, qIdx), withoutPrefix.substring(qIdx + 1))
      else
        (withoutPrefix, "")

    // Parse qualifiers into a Map
    val qualifiers: Map[String, String] =
      if (qualifierStr.isEmpty) Map.empty
      else
        qualifierStr
          .split('&')
          .map { kv =>
            val idx = kv.indexOf('=')
            if (idx > 0) kv.substring(0, idx) -> kv.substring(idx + 1)
            else kv -> ""
          }
          .toMap

    // Split version (everything after @)
    val atIdx = pathVersion.indexOf('@')
    val (path, version) =
      if (atIdx >= 0)
        (pathVersion.substring(0, atIdx), pathVersion.substring(atIdx + 1))
      else
        (pathVersion, "")

    // Split groupId and artifactId (last / in path)
    val lastSlash = path.lastIndexOf('/')
    if (lastSlash < 0) return None

    val groupId = path.substring(0, lastSlash)
    val artifactId = path.substring(lastSlash + 1)

    Some(PurlParts(groupId, artifactId, version, qualifiers))
  }

  /** Check if a pURL has a specific qualifier with a specific value.
    *
    * Example: `hasQualifier(purl, "packaging", "sources")` checks for
    * `?packaging=sources` in the pURL's query string.
    */
  def hasQualifier(purl: String, key: String, value: String): Boolean = {
    parse(purl).exists(_.qualifiers.get(key).contains(value))
  }

  /** Extract just the artifactId from a pURL. */
  def artifactIdOf(purl: String): Option[String] = parse(purl).map(_.artifactId)

  /** Normalize a pURL by stripping qualifiers (everything after ?). */
  def normalize(purl: String): String = {
    val idx = purl.indexOf('?')
    if (idx >= 0) purl.substring(0, idx) else purl
  }

  /** Strip `-sources` and `-javadoc` suffixes from a version string.
    *
    * The reference metadata scanner puts the classifier in the version (e.g.,
    * `1.6.1-sources`), while Goat Rodeo puts it in the qualifier (e.g.,
    * `1.6.1?packaging=sources`). This normalization allows version comparison
    * across tools.
    */
  def stripClassifierFromVersion(version: String): String = {
    var v = version
    if (v.endsWith("-sources")) v = v.substring(0, v.length - "-sources".length)
    if (v.endsWith("-javadoc")) v = v.substring(0, v.length - "-javadoc".length)
    if (v.endsWith("-javadocs"))
      v = v.substring(0, v.length - "-javadocs".length)
    v
  }
}
