/* Copyright 2026 David Pollak, Spice Labs, Inc. & Contributors
   Apache 2.0. */

package io.spicelabs.goatrodeo.omnibor.strategies

import io.spicelabs.goatrodeo.omnibor.ToProcess
import io.spicelabs.goatrodeo.util.Config
import io.spicelabs.goatrodeo.util.FileWrapper
import org.json4s.*
import org.json4s.native.JsonMethods.*
import munit.FunSuite

import java.io.File

/** Tests that Goat Rodeo finds the same pURLs as Syft for JARs containing
  * multiple embedded Maven packages (shaded/fat JARs).
  *
  * '''What this tests:'''
  * For each JAR where Syft found multiple pURLs, Goat Rodeo's
  * `buildGraphFromArtifactWrapper` must also find all of those pURLs via
  * `store.purls()`. This is the "Syft parity" requirement: Goat Rodeo must
  * discover every embedded package that Syft discovers.
  *
  * '''Why this matters:'''
  * A shaded JAR (e.g., an AWS SDK uber-JAR) contains classes from many
  * upstream packages. Each package has its own GAV in
  * `META-INF/maven/groupId/artifactId/pom.properties`. Syft reads all of
  * these and emits a pURL for each. Goat Rodeo's `extractAllEmbeddedGavs`
  * (Maven.scala) already collects all embedded GAVs, but `getPurls` and
  * `applyAccumulatedAugmentation` only emit ONE pURL — the "primary" GAV
  * selected by `determinePrimaryGav`. The non-primary GAVs are collected
  * but never turned into pURLs. These tests will fail until that gap is
  * closed.
  *
  * '''Test data source:'''
  * `src/test/resources/syft_multiple_purls.json` was generated by running
  * Syft v1.45.1 against every `.jar`, `.war`, `.ear`, and `.hpi` file in
  * `test_data/`. Only the 164 files where Syft found more than one pURL
  * are included. Each entry contains the JAR path and the sorted list of
  * pURLs Syft found.
  *
  * '''Expected initial state:''' RED — all tests fail because Goat Rodeo
  * only emits one pURL per JAR.
  *
  * '''LLM Summary:''' This is the baseline test suite for "multiple pURLs
  * per JAR" (Syft parity). Each test runs `ToProcess.buildGraphFromArtifactWrapper`
  * on a JAR, collects `store.purls()`, and asserts that every pURL Syft
  * found is also present in Goat Rodeo's output. The test allows Goat Rodeo
  * to find additional pURLs (superset is OK) but requires that no Syft
  * pURL is missing.
  */
class MultiplePurlSuite extends FunSuite {

  test("JSON resource loads correctly") {
    val entries = MultiplePurlSuite.loadEntries()
    assert(entries.nonEmpty, "No entries loaded from syft_multiple_purls.json")
    assert(entries.length == 164, s"Expected 164 entries, got ${entries.length}")
  }

  // Register one test per JAR. Each test runs Goat Rodeo on the JAR and
  // checks that every pURL Syft found is also in Goat Rodeo's output.
  //
  // Test theory: For JAR X, Syft found pURLs P1..Pn. Goat Rodeo's
  // buildGraphFromArtifactWrapper processes the JAR, collects pURLs via
  // store.addPurl(), and store.purls() returns the accumulated set. If
  // Goat Rodeo misses any Pi, the test fails with a message listing the
  // missing pURLs.
  //
  // Requirement: Syft parity — Goat Rodeo must find at least every pURL
  // that Syft finds. Finding additional pURLs (superset) is acceptable.
  val loadedEntries = MultiplePurlSuite.loadEntries()
  loadedEntries.foreach { entry =>
    test(s"Syft parity: ${entry.name} (${entry.purls.size} pURLs)") {
      val jarFile = File(entry.path)
      assert(
        jarFile.exists(),
        s"Test data file not found: ${entry.path}. Run from project root."
      )

      val artifact = FileWrapper(jarFile, entry.path, None)
      val store = ToProcess.buildGraphFromArtifactWrapper(
        artifact,
        args = Config()
      )

      val goatRodeoPurls: Set[String] = store.purls().toSet
      val syftPurls: Set[String] = entry.purls.toSet

      // Check that every pURL Syft found is also found by Goat Rodeo.
      // Goat Rodeo finding extra pURLs is OK (superset is acceptable).
      val missing = syftPurls -- goatRodeoPurls

      assert(
        missing.isEmpty,
        s"""Goat Rodeo is missing ${missing.size} of ${syftPurls.size} pURLs that Syft found.
           |
           |JAR: ${entry.path}
           |Syft found ${syftPurls.size} pURLs, Goat Rodeo found ${goatRodeoPurls.size}.
           |
           |Missing pURLs (in Syft but not in Goat Rodeo):
           |${missing.toList.sorted.map(p => s"  - $p").mkString("\n")}
           |
           |Goat Rodeo pURLs found:
           |${goatRodeoPurls.toList.sorted.map(p => s"  - $p").mkString("\n")}
           |""".stripMargin
      )
    }
  }
}

object MultiplePurlSuite {
  case class SyftEntry(name: String, path: String, purls: List[String])

  def loadEntries(): Vector[SyftEntry] = {
    val is = classOf[MultiplePurlSuite].getClassLoader.getResourceAsStream("syft_multiple_purls.json")
    if (is == null) return Vector.empty

    val content = try {
      scala.io.Source.fromInputStream(is).mkString
    } finally is.close()

    val json = parse(content)

    json match {
      case JArray(arr) =>
        arr.map { entry =>
          val obj = entry.asInstanceOf[JObject].obj
          val name = obj.find(_._1 == "name").map(_._2).collect { case JString(s) => s }.getOrElse("")
          val path = obj.find(_._1 == "path").map(_._2).collect { case JString(s) => s }.getOrElse("")
          val purls = obj.find(_._1 == "purls").map(_._2).collect {
            case JArray(pa) => pa.collect { case JString(s) => s }
          }.getOrElse(List.empty)
          SyftEntry(name, path, purls)
        }.toVector
      case _ => Vector.empty
    }
  }
}
