/* Copyright 2026 David Pollak, Spice Labs, Inc. & Contributors
   Apache 2.0. */

package io.spicelabs.goatrodeo.omnibor.strategies

import io.spicelabs.goatrodeo.omnibor.EdgeType
import io.spicelabs.goatrodeo.omnibor.MemStorage
import io.spicelabs.goatrodeo.omnibor.MetadataKeyConstants
import io.spicelabs.goatrodeo.util.FileWrapper
import io.spicelabs.goatrodeo.util.GitOIDUtils
import io.spicelabs.goatrodeo.util.PomParser
import io.spicelabs.goatrodeo.util.PomParser.ParsedPom
import munit.FunSuite

import java.io.File
import java.nio.file.Files
import java.util.zip.ZipFile
import scala.io.Source
import scala.jdk.CollectionConverters.given

/* Phase 5: Metadata Parity — Sources and Javadoc JARs
 *
 * '''What this suite tests:'''
 *   - REQ-5: For sources and javadoc JARs in the test corpus, Goat Rodeo
 *     pURLs must either match what the reference scanner finds or
 *     be better than what the reference scanner finds.
 *   - GAP-6: Metadata parity tests for sources/javadoc JARs
 *   - HS-4: Tests use the ACTUAL test corpus — real JAR files from
 *     `/data/test_data/`. Expected pURLs are extracted at test time by
 *     unzipping each JAR and reading its `META-INF/maven/.../pom.properties`
 *     entries.
 *
 * '''What this suite does NOT test:'''
 *   - Synthetic JARs (those are in Phase4SecondaryClassifierSuite)
 *   - Regular JAR metadata parity (that's MultiplePurlSuite, Phase 6)
 *   - Maven Central validation (that's BestPurlSuite, Phase 6)
 *
 * '''LLM context:''' This suite verifies that Goat Rodeo finds all pURLs
 * from embedded pom.properties in sources and javadoc JARs in the real
 * test corpus, and that its pURL count and artifactId set are at least
 * as comprehensive as the reference scanner output. It does NOT use
 * pre-computed data — it opens each JAR at test time, reads
 * pom.properties, builds expected pURLs, and compares against what
 * Goat Rodeo actually emits. It also loads static metadata ground truth.
 *
 * '''Test corpus stats:'''
 *   - 3051 sources JARs (files ending in `-sources.jar`)
 *   - 1 javadoc JAR (`wps-demo-1.3.0-javadoc.jar`)
 *   - 2995 sources JARs with companion POM
 *   - 56 standalone sources JARs (no main JAR, no POM)
 *
 * '''Sampling:''' Tests 5.3-5.8 sample from the corpus to keep test
 * runtime reasonable (~5 minutes). The sampling is deterministic (sorted
 * by path, every Nth file) to ensure reproducibility.
 */
class Phase5MetadataParitySourcesJavadocSuite extends FunSuite {

  // =========================================================================
  // Metadata ground truth (generated by reference scanner, loaded at test time)
  // =========================================================================

  private val metadataEntries =
    MetadataGroundTruth.loadEntries("metadata_sources_javadocs.json")

  // =========================================================================
  // Test corpus discovery
  // =========================================================================

  private val testDataDir = new File("test_data")

  /** All sources JARs in the corpus, sorted by path for determinism. */
  private lazy val sourcesJars: Vector[File] = {
    findFiles(testDataDir, _.toLowerCase.endsWith("-sources.jar"))
  }

  /** All javadoc JARs in the corpus, sorted by path for determinism. */
  private lazy val javadocJars: Vector[File] = {
    findFiles(
      testDataDir,
      f =>
        f.toLowerCase.endsWith("-javadoc.jar") ||
          f.toLowerCase.endsWith("-javadocs.jar")
    )
  }

  /** Recursively find files matching a predicate. */
  private def findFiles(dir: File, pred: String => Boolean): Vector[File] = {
    if (!dir.exists()) return Vector.empty
    val result = scala.collection.mutable.ArrayBuffer[File]()
    def scan(d: File): Unit = {
      val entries = d.listFiles()
      if (entries != null) {
        for (e <- entries) {
          if (e.isFile && pred(e.getName)) {
            result += e
          } else if (e.isDirectory) {
            scan(e)
          }
        }
      }
    }
    scan(dir)
    result.toVector.sorted
  }

  /** Get the companion POM file for a JAR, if it exists.
    *
    * For `foo-1.0-sources.jar`, the companion POM is `foo-1.0.pom` (the POM is
    * shared between the main JAR and the sources JAR — Maven does not publish
    * separate POMs for sources/javadoc JARs). For `foo-1.0.jar`, the companion
    * POM is `foo-1.0.pom`.
    */
  private def companionPom(jarFile: File): Option[File] = {
    val basePath = jarFile.getAbsolutePath
    // Strip -sources.jar, -javadoc.jar, -javadocs.jar, .jar, .war, etc.
    val strippedPath = basePath
      .stripSuffix("-sources.jar")
      .stripSuffix("-javadoc.jar")
      .stripSuffix("-javadocs.jar")
      .stripSuffix(".jar")
      .stripSuffix(".war")
      .stripSuffix(".ear")
      .stripSuffix(".hpi")
    val pomPath = strippedPath + ".pom"
    val pomFile = new File(pomPath)
    if (pomFile.exists()) Some(pomFile) else None
  }

  /** Get the companion main JAR for a sources JAR, if it exists.
    *
    * For `foo-1.0-sources.jar`, the main JAR is `foo-1.0.jar`.
    */
  private def companionMainJar(jarFile: File): Option[File] = {
    val basePath = jarFile.getAbsolutePath
    if (basePath.endsWith("-sources.jar")) {
      val mainJarPath = basePath.stripSuffix("-sources.jar") + ".jar"
      val mainJarFile = new File(mainJarPath)
      if (mainJarFile.exists()) Some(mainJarFile) else None
    } else None
  }

  // =========================================================================
  // Expected pURL extraction from JAR at test time (HS-4)
  // =========================================================================

  /** Case class for a parsed pom.properties tuple. */
  case class PomProps(groupId: String, artifactId: String, version: String)

  /** Extract all pom.properties tuples from a JAR at test time.
    *
    * Opens the JAR as a ZipFile, finds all `META-INF/maven/.../pom.properties`
    * entries, parses each to extract groupId/artifactId/version.
    *
    * This is the "expected" data source — NOT pre-computed, NOT cached, NOT
    * from a JSON file. Each JAR is opened and parsed fresh at test time per
    * HS-4.
    *
    * @param jarFile
    *   the JAR file to extract from
    * @return
    *   a vector of parsed pom.properties tuples (deduplicated)
    */
  private def extractPomProperties(jarFile: File): Vector[PomProps] = {
    val zip = new ZipFile(jarFile)
    try {
      val entries = zip
        .entries()
        .asScala
        .toVector
        .filter { e =>
          val lower = e.getName.toLowerCase
          lower.startsWith("meta-inf/maven/") &&
          lower.endsWith("/pom.properties")
        }

      val tuples = entries.flatMap { entry =>
        val content = scala.io.Source
          .fromInputStream(
            zip.getInputStream(entry)
          )
          .mkString
        parsePomProperties(content)
      }

      tuples.distinct
    } finally {
      zip.close()
    }
  }

  /** Parse a pom.properties file content to extract groupId/artifactId/version.
    *
    * Mimics the Maven pipeline's `parsePropertiesString` — lowercases keys,
    * strips comments, extracts key=value pairs.
    */
  private def parsePomProperties(content: String): Option[PomProps] = {
    val props = content.linesIterator
      .map(_.trim)
      .filterNot(_.startsWith("#"))
      .filter(_.contains("="))
      .map { line =>
        val idx = line.indexOf('=')
        line.substring(0, idx).trim.toLowerCase -> line.substring(idx + 1).trim
      }
      .toMap

    for {
      g <- props.get("groupid")
      a <- props.get("artifactid")
      v <- props.get("version")
      if g.nonEmpty && a.nonEmpty && v.nonEmpty
    } yield PomProps(g, a, v)
  }

  /** Build expected pURL set from pom.properties tuples.
    *
    * Each tuple produces a pURL string:
    * `pkg:maven/<groupId>/<artifactId>@<version>?packaging=sources` for sources
    * JARs, or `pkg:maven/<groupId>/<artifactId>@<version>?classifier=javadoc`
    * for javadoc JARs.
    *
    * Note: These are the EXPECTED pURLs — the minimum set Goat Rodeo must find.
    * Goat Rodeo may find additional pURLs (from manifest, embedded pom.xml,
    * etc.), which is acceptable (superset).
    */
  private def buildExpectedPurls(
      tuples: Vector[PomProps],
      classifier: String
  ): Set[String] = {
    tuples.map { t =>
      s"pkg:maven/${t.groupId}/${t.artifactId}@${t.version}?$classifier"
    }.toSet
  }

  // =========================================================================
  // Process a corpus JAR through the Goat Rodeo pipeline
  // =========================================================================

  /** Process a sources or javadoc JAR through the full Maven pipeline.
    *
    * Copies the JAR (and companion POM if it exists) to a temp directory, then
    * calls `processDirectoryWithStore` to run the full pipeline. This exercises
    * the companion POM bundling (REQ-8) and processing order (POM → Sources →
    * Javadoc → JAR) (REQ-4).
    *
    * Returns the store with all emitted pURLs and metadata.
    */
  private def processCorpusJar(
      jarFile: File
  ): MemStorage = {
    MavenTestHelpers.withTempDir(s"phase5-${jarFile.getName}") { dir =>
      val destJar = new File(dir, jarFile.getName)
      Files.copy(jarFile.toPath, destJar.toPath)

      // Copy companion POM if it exists
      companionPom(jarFile).foreach { pom =>
        val destPom = new File(dir, pom.getName)
        Files.copy(pom.toPath, destPom.toPath)
      }

      // Copy companion main JAR if it exists (so computeMavenFiles bundles
      // the sources JAR as a companion, not standalone)
      companionMainJar(jarFile).foreach { mainJar =>
        val destMain = new File(dir, mainJar.getName)
        Files.copy(mainJar.toPath, destMain.toPath)
      }

      val store = MavenTestHelpers.processDirectoryWithStore(dir)
      store
    }
  }

  /** Extract pURLs emitted by Goat Rodeo for a specific JAR.
    *
    * Computes the gitoid of the JAR, reads the corresponding Item from the
    * store, and extracts the `alias:from` connections (pURLs).
    */
  private def extractGoatRodeoPurls(
      store: MemStorage,
      jarFile: File
  ): Set[String] = {
    val artifact = FileWrapper(jarFile, jarFile.getName, None)
    val (gitoid, _) = GitOIDUtils.computeAllHashes(artifact)

    store.read(gitoid) match {
      case Some(item) =>
        item.connections
          .filter(_._1 == EdgeType.aliasFrom)
          .map(_._2)
          .filter(_.startsWith("pkg:"))
          .toSet
      case None => Set.empty
    }
  }

  /** Extract the canonical pURL from a JAR's metadata.
    *
    * Reads the gitoid Item's metadata and looks for the `CanonicalPurl` key in
    * the `extra` map.
    */
  private def extractCanonicalPurl(
      store: MemStorage,
      jarFile: File
  ): Option[String] = {
    val artifact = FileWrapper(jarFile, jarFile.getName, None)
    val (gitoid, _) = GitOIDUtils.computeAllHashes(artifact)

    store.read(gitoid).flatMap { item =>
      item.bodyAsItemMetaData.flatMap { meta =>
        meta.extra
          .get(MetadataKeyConstants.CANONICAL_PURL)
          .flatMap(_.headOption.map(_.value))
      }
    }
  }

  /** Parse a companion POM file to extract groupId/artifactId/version.
    *
    * Uses the production PomParser (same code Goat Rodeo uses), so the test
    * verifies the actual parsing behavior, not a test-only reimpl.
    */
  private def parseCompanionPom(pomFile: File): Option[ParsedPom] = {
    val content = Source.fromFile(pomFile).mkString
    PomParser.parse(content)
  }

  /** Assert Goat Rodeo finds at least as many packages as the reference
    * metadata scanner.
    *
    * Compares:
    *   1. pURL count: Goat Rodeo >= reference scanner 2. artifactId superset:
    *      Goat Rodeo's artifactIds must include all artifactIds the reference
    *      scanner found
    *
    * The groupId may differ — Goat Rodeo uses companion POM, the scanner may
    * use filename — but the artifactId should match. This verifies Goat Rodeo
    * discovers at least all the same packages.
    */
  private def assertMetadataParity(
      jarFile: File,
      goatPurls: Set[String]
  ): Unit = {
    MetadataGroundTruth.findEntry(metadataEntries, jarFile.getName).foreach {
      entry =>
        // Count check
        assert(
          goatPurls.size >= entry.purls.size,
          s"""Goat Rodeo found ${goatPurls.size} pURLs but reference metadata found ${entry.purls.size}.
           |
           |Goat Rodeo pURLs:
           |  ${goatPurls.toList.sorted.mkString("\n  ")}
           |
           |Reference metadata pURLs:
           |  ${entry.purls.sorted.mkString("\n  ")}
           |
           |JAR: ${jarFile.getAbsolutePath}
           |""".stripMargin
        )

        // ArtifactId superset check
        val goatArtifactIds = goatPurls.flatMap(PurlParts.artifactIdOf)
        val metadataArtifactIds =
          entry.purls.flatMap(PurlParts.artifactIdOf).toSet
        val missingArtifacts = metadataArtifactIds -- goatArtifactIds
        assert(
          missingArtifacts.isEmpty,
          s"""Goat Rodeo is missing ${missingArtifacts.size} artifactIds found by reference scanner.
           |
           |Missing artifactIds: ${missingArtifacts.toList.sorted
              .mkString(", ")}
           |Goat Rodeo artifactIds: ${goatArtifactIds.toList.sorted
              .mkString(", ")}
           |Reference artifactIds: ${metadataArtifactIds.toList.sorted
              .mkString(", ")}
           |
           |JAR: ${jarFile.getAbsolutePath}
           |""".stripMargin
        )
    }
  }

  // =========================================================================
  // Test 5.1: Discover sources JARs in test corpus
  // =========================================================================
  //
  // What it tests:
  //   The test corpus contains sources JARs (files ending in
  //   `-sources.jar`) and they are discoverable.
  //
  // Why it's relevant:
  //   Before testing parity, we need to know what sources JARs exist
  //   in the corpus. This is a setup/verification test.
  //
  // Requirement section:
  //   HS-4 — use the actual test corpus.
  //
  // Theory:
  //   Scan `/data/test_data/` for files matching `*-sources.jar`.
  //   Assert count > 0.

  test("Test 5.1: Discover sources JARs in test corpus") {
    assert(
      sourcesJars.nonEmpty,
      "Test corpus should contain at least one sources JAR (-sources.jar)"
    )
    assert(
      sourcesJars.length > 100,
      s"Expected >100 sources JARs, found ${sourcesJars.length}"
    )
  }

  // =========================================================================
  // Test 5.2: Discover javadoc JARs in test corpus
  // =========================================================================
  //
  // What it tests:
  //   The test corpus contains at least one javadoc JAR.
  //
  // Why it's relevant:
  //   Same as 5.1 but for javadoc JARs.
  //
  // Requirement section:
  //   HS-4.
  //
  // Theory:
  //   Scan `/data/test_data/` for files matching `*-javadoc.jar` or
  //   `*-javadocs.jar`. Assert count > 0.

  test("Test 5.2: Discover javadoc JARs in test corpus") {
    assert(
      javadocJars.nonEmpty,
      "Test corpus should contain at least one javadoc JAR (-javadoc.jar)"
    )
    assert(
      javadocJars.length >= 1,
      s"Expected >=1 javadoc JAR, found ${javadocJars.length}"
    )
  }

  // =========================================================================
  // Test 5.3: Sources JAR pURLs match embedded pom.properties
  // =========================================================================
  //
  // What it tests:
  //   For each sources JAR in the corpus (sampled), Goat Rodeo finds at
  //   least every pURL that can be derived from the JAR's embedded
  //   `pom.properties` files. All pURLs include `?packaging=sources`.
  //
  // Why it's relevant:
  //   This is the core metadata parity test for sources JARs. The
  //   reference scanner reads `META-INF/maven/*/pom.properties` in
  //   every JAR. Goat Rodeo must find at least the same pURLs (plus
  //   classifiers).
  //
  // Requirement section:
  //   REQ-5 — "Goat Rodeo pURLs must either match what the reference
  //   scanner finds or be better than what the reference scanner finds."
  //
  // Theory:
  //   For each sampled sources JAR:
  //   1. Extract expected pURLs by unzipping the JAR and reading all
  //      `META-INF/maven/*/pom.properties` files (at test time).
  //   2. Build expected pURL set: for each `pom.properties`, construct
  //      `pkg:maven/<groupId>/<artifactId>@<version>?packaging=sources`.
  //   3. Run Goat Rodeo on the JAR (directory-based setup).
  //   4. Assert Goat Rodeo's pURL set is a superset of expected pURLs
  //      (after normalizing — stripping qualifiers from Goat Rodeo pURLs
  //      for comparison, since Goat Rodeo adds `?packaging=sources` which
  //      the reference scanner doesn't).
  //   5. Assert ALL Goat Rodeo pURLs contain `?packaging=sources`.
  //   6. Assert Goat Rodeo pURL count <= expected count + 2 (tolerance for
  //      manifest-derived extras).

  // Sample 50 sources JARs deterministically (every Nth file)
  private val sampledSourcesJars: Vector[File] = {
    if (sourcesJars.isEmpty) Vector.empty
    else {
      val step = math.max(1, sourcesJars.length / 50)
      sourcesJars.indices.filter(_ % step == 0).map(sourcesJars(_)).toVector
    }
  }

  sampledSourcesJars.foreach { jarFile =>
    val props = extractPomProperties(jarFile)
    // Only test JARs that have at least 1 pom.properties entry
    if (props.nonEmpty) {
      test(
        s"Test 5.3: ${jarFile.getName} — pURLs match pom.properties (${props.size} entries)"
      ) {
        val expected = buildExpectedPurls(props, "packaging=sources")

        val store = processCorpusJar(jarFile)
        val goatPurls = extractGoatRodeoPurls(store, jarFile)

        // All Goat Rodeo pURLs must have ?packaging=sources (structured check)
        val withoutClassifier =
          goatPurls.filterNot(PurlParts.hasQualifier(_, "packaging", "sources"))
        assert(
          withoutClassifier.isEmpty,
          s"""pURLs without ?packaging=sources:
             |  ${withoutClassifier.toList.sorted.mkString("\n  ")}
             |
             |All pURLs: ${goatPurls.toList.sorted.mkString("\n  ")}
             |Expected (from pom.properties): ${expected.toList.sorted.mkString(
              "\n  "
            )}
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )

        val normalizedGoat = goatPurls.map(PurlParts.normalize)
        val normalizedExpected = expected.map(PurlParts.normalize)

        // Goat Rodeo must find at least all expected pURLs (superset)
        val missing = normalizedExpected -- normalizedGoat
        assert(
          missing.isEmpty,
          s"""Goat Rodeo is missing ${missing.size} of ${expected.size} expected pURLs.
             |
             |Missing (in pom.properties but not in Goat Rodeo):
             |  ${missing.toList.sorted.mkString("\n  ")}
             |
             |Goat Rodeo pURLs:
             |  ${goatPurls.toList.sorted.mkString("\n  ")}
             |
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )

        // Goat Rodeo pURL count should not be wildly inflated
        // (tolerance: +2 for manifest/embedded-pom-derived extras)
        assert(
          goatPurls.size <= expected.size + 2,
          s"""Goat Rodeo found ${goatPurls.size} pURLs but expected only ${expected.size}.
             |This suggests garbage pURLs or duplicate emission.
             |
             |Goat Rodeo pURLs:
             |  ${goatPurls.toList.sorted.mkString("\n  ")}
             |
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )

        // Metadata ground truth parity: Goat Rodeo must find at least
        // as many packages as the reference scanner.
        assertMetadataParity(jarFile, goatPurls)
      }
    }
  }

  // =========================================================================
  // Test 5.4: Javadoc JAR pURLs match embedded pom.properties
  // =========================================================================
  //
  // What it tests:
  //   Same as 5.3 but for javadoc JARs with `?classifier=javadoc`.
  //
  // Requirement section:
  //   REQ-5.

  javadocJars.foreach { jarFile =>
    val props = extractPomProperties(jarFile)
    test(
      s"Test 5.4: ${jarFile.getName} — pURLs match pom.properties (${props.size} entries)"
    ) {
      val expected = buildExpectedPurls(props, "classifier=javadoc")

      val store = processCorpusJar(jarFile)
      val goatPurls = extractGoatRodeoPurls(store, jarFile)

      // Must have at least 1 pURL — prevents vacuous pass where Goat Rodeo
      // emits nothing and the classifier check trivially passes on empty set.
      assert(
        goatPurls.nonEmpty,
        s"Goat Rodeo should emit at least 1 pURL for javadoc JAR.\nJAR: ${jarFile.getAbsolutePath}"
      )

      // All Goat Rodeo pURLs must have ?classifier=javadoc (structured check)
      val withoutClassifier =
        goatPurls.filterNot(PurlParts.hasQualifier(_, "classifier", "javadoc"))
      assert(
        withoutClassifier.isEmpty,
        s"""pURLs without ?classifier=javadoc:
           |  ${withoutClassifier.toList.sorted.mkString("\n  ")}
           |
           |All pURLs: ${goatPurls.toList.sorted.mkString("\n  ")}
           |JAR: ${jarFile.getAbsolutePath}
           |""".stripMargin
      )

      if (props.nonEmpty) {
        val normalizedGoat = goatPurls.map(PurlParts.normalize)
        val normalizedExpected = expected.map(PurlParts.normalize)

        // Goat Rodeo must find at least all expected pURLs (superset)
        val missing = normalizedExpected -- normalizedGoat
        assert(
          missing.isEmpty,
          s"""Goat Rodeo is missing ${missing.size} of ${expected.size} expected pURLs.
             |
             |Missing:
             |  ${missing.toList.sorted.mkString("\n  ")}
             |
             |Goat Rodeo pURLs:
             |  ${goatPurls.toList.sorted.mkString("\n  ")}
             |
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )
      }

      // Metadata ground truth parity: Goat Rodeo must find at least
      // as many packages as the reference scanner. This runs even when
      // pom.properties is absent (the javadoc JAR has no pom.properties).
      assertMetadataParity(jarFile, goatPurls)
    }
  }

  // =========================================================================
  // Test 5.5: Sources JAR with companion POM uses POM for canonical pURL
  // =========================================================================
  //
  // What it tests:
  //   For sources JARs in the corpus that have a companion `.pom` file,
  //   the canonical pURL uses the companion POM's groupId/artifactId/version
  //   (not the filename or manifest).
  //
  // Why it's relevant:
  //   Verifies Phase 2 (canonical priority) works against real corpus
  //   data for sources JARs.
  //
  // Requirement section:
  //   REQ-3 + REQ-5.

  private val sourcesJarsWithPom: Vector[File] = {
    sampledSourcesJars.filter(companionPom(_).isDefined)
  }

  // Sample 10 sources JARs with companion POMs for this test
  private val sampledWithPom: Vector[File] = {
    if (sourcesJarsWithPom.isEmpty) Vector.empty
    else {
      val step = math.max(1, sourcesJarsWithPom.length / 10)
      sourcesJarsWithPom.indices
        .filter(_ % step == 0)
        .map(sourcesJarsWithPom(_))
        .toVector
    }
  }

  sampledWithPom.foreach { jarFile =>
    test(s"Test 5.5: ${jarFile.getName} — canonical pURL from companion POM") {
      // Parse the companion POM to get expected coordinates
      val pomOpt = companionPom(jarFile)
      assert(pomOpt.isDefined, s"Companion POM should exist for: $jarFile")
      val parsedPom = parseCompanionPom(pomOpt.get)
      assert(
        parsedPom.isDefined,
        s"Failed to parse companion POM: ${pomOpt.get}"
      )

      val pomG = parsedPom.get.groupId.orElse(parsedPom.get.parentGroupId)
      val pomA = parsedPom.get.artifactId
      val pomV = parsedPom.get.version.orElse(parsedPom.get.parentVersion)

      assert(pomG.isDefined, s"POM groupId not found: ${pomOpt.get}")
      assert(pomA.isDefined, s"POM artifactId not found: ${pomOpt.get}")
      assert(pomV.isDefined, s"POM version not found: ${pomOpt.get}")

      val store = processCorpusJar(jarFile)
      val canonicalPurlOpt = extractCanonicalPurl(store, jarFile)

      assert(
        canonicalPurlOpt.isDefined,
        s"Canonical pURL should be present for sources JAR with companion POM.\nJAR: ${jarFile.getAbsolutePath}"
      )

      val canonicalPurl = canonicalPurlOpt.get

      // Structured check: canonical pURL must have ?packaging=sources qualifier
      assert(
        PurlParts.hasQualifier(canonicalPurl, "packaging", "sources"),
        s"Canonical pURL should have ?packaging=sources.\nCanonical: $canonicalPurl\nJAR: ${jarFile.getAbsolutePath}"
      )

      // Structured comparison: canonical pURL's GAV must match the POM's GAV.
      // This is the core assertion that was missing — previously the test
      // only checked that a canonical pURL existed with the right qualifier,
      // but never verified the coordinates came from the POM.
      val purlParts = PurlParts.parse(canonicalPurl)
      assert(
        purlParts.isDefined,
        s"Failed to parse canonical pURL: $canonicalPurl"
      )

      purlParts.foreach { parts =>
        assert(
          parts.groupId == pomG.get,
          s"""Canonical pURL groupId should come from companion POM, not filename or manifest.
             |
             |Expected (from POM): ${pomG.get}
             |Actual (from pURL):  ${parts.groupId}
             |Canonical pURL: $canonicalPurl
             |POM file: ${pomOpt.get.getAbsolutePath}
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )
        assert(
          parts.artifactId == pomA.get,
          s"""Canonical pURL artifactId should come from companion POM.
             |
             |Expected (from POM): ${pomA.get}
             |Actual (from pURL):  ${parts.artifactId}
             |Canonical pURL: $canonicalPurl
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )
        assert(
          parts.version == pomV.get,
          s"""Canonical pURL version should come from companion POM.
             |
             |Expected (from POM): ${pomV.get}
             |Actual (from pURL):  ${parts.version}
             |Canonical pURL: $canonicalPurl
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )
      }

      // Also verify against metadata ground truth
      val goatPurls = extractGoatRodeoPurls(store, jarFile)
      assertMetadataParity(jarFile, goatPurls)
    }
  }

  // =========================================================================
  // Test 5.6: Sources JAR canonical pURL in metadata
  // =========================================================================
  //
  // What it tests:
  //   For sources JARs in the corpus, the gitoid Item's metadata contains
  //   `CanonicalPurl` key with correct value (including `?packaging=sources`).
  //
  // Requirement section:
  //   GAP-7 + REQ-5.

  // Reuse sampled sources JARs (first 5 with pom.properties)
  private val sampledForMetadata: Vector[File] = {
    sampledSourcesJars
      .filter(j => extractPomProperties(j).nonEmpty)
      .take(5)
  }

  sampledForMetadata.foreach { jarFile =>
    test(s"Test 5.6: ${jarFile.getName} — canonical pURL in metadata") {
      val store = processCorpusJar(jarFile)
      val canonicalPurlOpt = extractCanonicalPurl(store, jarFile)

      assert(
        canonicalPurlOpt.isDefined,
        s"CanonicalPurl metadata key should be present.\nJAR: ${jarFile.getAbsolutePath}"
      )

      val canonicalPurl = canonicalPurlOpt.get
      assert(
        canonicalPurl.startsWith("pkg:maven/"),
        s"Canonical pURL should start with pkg:maven/.\nCanonical: $canonicalPurl"
      )
      assert(
        PurlParts.hasQualifier(canonicalPurl, "packaging", "sources"),
        s"Canonical pURL should have ?packaging=sources.\nCanonical: $canonicalPurl"
      )
    }
  }

  // =========================================================================
  // Test 5.7: Standalone sources JAR (no companion POM) still emits pURLs
  // =========================================================================
  //
  // What it tests:
  //   Sources JARs without a companion POM (no main JAR in the same
  //   directory) still emit pURLs with `?packaging=sources`.
  //
  // Why it's relevant:
  //   `computeMavenFiles` has a second pass that claims standalone
  //   sources/javadoc JARs. These get `MavenToProcess(a, None, None, None, None)`
  //   — no companion POM. The canonical pURL falls back to JAR contents
  //   then filename.
  //
  // Requirement section:
  //   REQ-5.

  private val standaloneSourcesJars: Vector[File] = {
    sourcesJars.filter { jar =>
      companionMainJar(jar).isEmpty && companionPom(jar).isEmpty
    }
  }

  // Sample 5 standalone sources JARs
  private val sampledStandalone: Vector[File] = {
    if (standaloneSourcesJars.isEmpty) Vector.empty
    else {
      val step = math.max(1, standaloneSourcesJars.length / 5)
      standaloneSourcesJars.indices
        .filter(_ % step == 0)
        .map(standaloneSourcesJars(_))
        .toVector
    }
  }

  sampledStandalone.foreach { jarFile =>
    test(s"Test 5.7: ${jarFile.getName} — standalone sources JAR emits pURLs") {
      val store = processCorpusJar(jarFile)
      val goatPurls = extractGoatRodeoPurls(store, jarFile)

      assert(
        goatPurls.nonEmpty,
        s"Standalone sources JAR should emit at least one pURL.\nJAR: ${jarFile.getAbsolutePath}"
      )

      // ALL pURLs must have ?packaging=sources (structured check)
      val withoutClassifier =
        goatPurls.filterNot(PurlParts.hasQualifier(_, "packaging", "sources"))
      assert(
        withoutClassifier.isEmpty,
        s"""Standalone sources JAR pURLs without ?packaging=sources:
           |  ${withoutClassifier.toList.sorted.mkString("\n  ")}
           |
           |All pURLs: ${goatPurls.toList.sorted.mkString("\n  ")}
           |JAR: ${jarFile.getAbsolutePath}
           |""".stripMargin
      )

      // Verify pURL coordinates are correct, not just non-empty.
      // For JARs with pom.properties: assert superset of expected pURLs.
      // For JARs without pom.properties: assert at least one pURL's
      // artifactId matches the filename-derived artifactId.
      val props = extractPomProperties(jarFile)
      if (props.nonEmpty) {
        val expected = buildExpectedPurls(props, "packaging=sources")
        val normalizedGoat = goatPurls.map(PurlParts.normalize)
        val normalizedExpected = expected.map(PurlParts.normalize)
        val missing = normalizedExpected -- normalizedGoat
        assert(
          missing.isEmpty,
          s"""Goat Rodeo is missing ${missing.size} of ${expected.size} expected pURLs (from pom.properties).
             |
             |Missing:
             |  ${missing.toList.sorted.mkString("\n  ")}
             |
             |Goat Rodeo pURLs:
             |  ${goatPurls.toList.sorted.mkString("\n  ")}
             |
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )
      } else {
        // No pom.properties — verify at least one pURL's artifactId
        // matches the filename-derived artifactId. This ensures the
        // pURL is not garbage.
        val fnameArt = {
          val name = jarFile.getName
          val stripped = name
            .stripSuffix("-sources.jar")
            .stripSuffix("-javadoc.jar")
            .stripSuffix("-javadocs.jar")
          val lastDash = stripped.lastIndexOf('-')
          if (lastDash > 0) stripped.substring(0, lastDash)
          else stripped
        }
        val goatArtifactIds = goatPurls.flatMap(PurlParts.artifactIdOf)
        assert(
          goatArtifactIds.contains(fnameArt),
          s"""No pURL artifactId matches the filename-derived artifactId '$fnameArt'.
             |
             |Goat Rodeo artifactIds: ${goatArtifactIds.toList.sorted.mkString(
              ", "
            )}
             |Filename-derived artifactId: $fnameArt
             |
             |Goat Rodeo pURLs:
             |  ${goatPurls.toList.sorted.mkString("\n  ")}
             |
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )
      }

      // Metadata ground truth parity
      assertMetadataParity(jarFile, goatPurls)
    }
  }

  // =========================================================================
  // Test 5.8: For any sources JAR in corpus, pURL count >= pom.properties count
  // =========================================================================
  //
  // What it tests:
  //   For any sources JAR, Goat Rodeo finds at least as many pURLs as
  //   there are embedded `pom.properties` entries.
  //
  // Requirement section:
  //   REQ-5.

  // Reuse sampled sources JARs
  sampledSourcesJars.foreach { jarFile =>
    val props = extractPomProperties(jarFile)
    if (props.nonEmpty) {
      test(
        s"Test 5.8: ${jarFile.getName} — pURL count >= pom.properties count (${props.size})"
      ) {
        val store = processCorpusJar(jarFile)
        val goatPurls = extractGoatRodeoPurls(store, jarFile)

        assert(
          goatPurls.size >= props.size,
          s"""Goat Rodeo found ${goatPurls.size} pURLs but expected >= ${props.size} (pom.properties count).
             |
             |Goat Rodeo pURLs:
             |  ${goatPurls.toList.sorted.mkString("\n  ")}
             |
             |Expected pom.properties tuples:
             |  ${props
              .map(p => s"${p.groupId}/${p.artifactId}@${p.version}")
              .mkString("\n  ")}
             |
             |JAR: ${jarFile.getAbsolutePath}
             |""".stripMargin
        )

        // Metadata ground truth parity
        assertMetadataParity(jarFile, goatPurls)
      }
    }
  }
}
