/* Copyright 2026 David Pollak, Spice Labs, Inc. & Contributors
   Apache 2.0. */

package io.spicelabs.goatrodeo.omnibor.strategies

import io.spicelabs.goatrodeo.omnibor.EdgeType
import io.spicelabs.goatrodeo.omnibor.MemStorage
import io.spicelabs.goatrodeo.omnibor.MetadataKeyConstants
import io.spicelabs.goatrodeo.util.FileWrapper
import io.spicelabs.goatrodeo.util.GitOIDUtils
import io.spicelabs.goatrodeo.util.PomParser
import io.spicelabs.goatrodeo.util.PomParser.ParsedPom
import munit.FunSuite

import java.io.File
import java.nio.file.Files
import scala.io.Source

/* Phase 6: Metadata Parity — Regular JARs and BestPurlSuite
 *
 * '''What this suite tests:'''
 *   - REQ-6: Goat Rodeo pURLs must either match what the reference scanner finds or be
 *     better than what the reference scanner finds for regular JARs.
 *   - GAP-5: MultiplePurlSuite (already passing — 113 tests, covered
 *     in Phase 2 rewrite).
 *   - GAP-8: BestPurlSuite (already passing — 2 tests).
 *   - Test 6.3: "Better than the reference scanner" — Goat Rodeo uses companion POM for
 *     canonical pURL, not the filename.
 *   - Test 6.4: Maven Central validation — canonical pURLs match
 *     coordinates verified to exist in Maven Central.
 *   - Test 6.6: Companion POM priority in full pipeline — canonical
 *     pURL comes from POM, not manifest or pom.properties.
 *
 * '''What this suite does NOT test:'''
 *   - Test 6.1 (MultiplePurlSuite) — already covered by MultiplePurlSuite
 *     (113 tests, rewritten in Phase 2).
 *   - Test 6.2 (BestPurlSuite) — already covered by BestPurlSuite
 *     (2 tests, passing).
 *   - Test 6.5 (pURL count >= reference scanner count) — implicitly covered by
 *     MultiplePurlSuite superset check (superset implies count >=).
 *   - Test 6.7 (property-based superset) — same as MultiplePurlSuite.
 *
 * '''Maven Central verification:'''
 * Each coordinate in Test 6.4 was manually verified to exist in Maven
 * Central at https://repo1.maven.org/maven2/ on 2026-07-08. No runtime
 * Maven Central queries are performed.
 *
 * '''LLM context:''' This suite verifies that Goat Rodeo produces pURLs
 * that (a) match real Maven Central artifacts and (b) are derived from
 * the companion POM rather than the filename — making them more accurate
 * than the reference scanner's filename-derived pURLs.
 */
class Phase6MetadataParityRegularBestPurlSuite extends FunSuite {

  // =========================================================================
  // Metadata ground truth (generated by reference scanner)
  // =========================================================================

  private val regularJarMetadata =
    MetadataGroundTruth.loadEntries("metadata_regular_jars_6_3.json")

  // =========================================================================
  // Helpers
  // =========================================================================

  /** Get the companion POM file for a JAR, if it exists.
    *
    * For `foo-1.0.jar`, the companion POM is `foo-1.0.pom`. For
    * `foo-1.0-sources.jar`, the companion POM is `foo-1.0.pom`.
    */
  private def companionPom(jarFile: File): Option[File] = {
    val basePath = jarFile.getAbsolutePath
    val strippedPath = basePath
      .stripSuffix("-sources.jar")
      .stripSuffix("-javadoc.jar")
      .stripSuffix("-javadocs.jar")
      .stripSuffix(".jar")
      .stripSuffix(".war")
      .stripSuffix(".ear")
      .stripSuffix(".hpi")
    val pomPath = strippedPath + ".pom"
    val pomFile = new File(pomPath)
    if (pomFile.exists()) Some(pomFile) else None
  }

  /** Parse a companion POM file to extract groupId/artifactId/version.
    *
    * Uses the production PomParser (same code Goat Rodeo uses), so the test
    * verifies the actual parsing behavior, not a test-only reimpl.
    */
  private def parseCompanionPom(pomFile: File): Option[ParsedPom] = {
    val content = Source.fromFile(pomFile).mkString
    PomParser.parse(content)
  }

  /** Process a JAR (with companion POM) through the full Maven pipeline.
    *
    * Copies the JAR and companion POM to a temp directory, then calls
    * processDirectoryWithStore to run the full pipeline.
    */
  private def processCorpusJar(jarFile: File): MemStorage = {
    MavenTestHelpers.withTempDir(s"phase6-${jarFile.getName}") { dir =>
      val destJar = new File(dir, jarFile.getName)
      Files.copy(jarFile.toPath, destJar.toPath)

      companionPom(jarFile).foreach { pom =>
        val destPom = new File(dir, pom.getName)
        Files.copy(pom.toPath, destPom.toPath)
      }

      MavenTestHelpers.processDirectoryWithStore(dir)
    }
  }

  /** Extract the canonical pURL from a JAR's metadata. */
  private def extractCanonicalPurl(
      store: MemStorage,
      jarFile: File
  ): Option[String] = {
    val artifact = FileWrapper(jarFile, jarFile.getName, None)
    val (gitoid, _) = GitOIDUtils.computeAllHashes(artifact)

    store.read(gitoid).flatMap { item =>
      item.bodyAsItemMetaData.flatMap { meta =>
        meta.extra
          .get(MetadataKeyConstants.CANONICAL_PURL)
          .flatMap(_.headOption.map(_.value))
      }
    }
  }

  /** Extract all pURLs (alias:from) for a JAR from the store. */
  private def extractGoatRodeoPurls(
      store: MemStorage,
      jarFile: File
  ): Set[String] = {
    val artifact = FileWrapper(jarFile, jarFile.getName, None)
    val (gitoid, _) = GitOIDUtils.computeAllHashes(artifact)

    store.read(gitoid) match {
      case Some(item) =>
        item.connections
          .filter(_._1 == EdgeType.aliasFrom)
          .map(_._2)
          .filter(_.startsWith("pkg:"))
          .toSet
      case None => Set.empty
    }
  }

  /** Extract the artifactId from a filename. `Agrona-0.1.jar` -> `Agrona`
    * `abris-0.0.1.jar` -> `abris`
    */
  private def filenameArtifactId(name: String): String = {
    val withoutExt = name.replaceAll("\\.(jar|war|ear|hpi)$", "")
    val lastDash = withoutExt.lastIndexOf('-')
    if (lastDash > 0) withoutExt.substring(0, lastDash)
    else withoutExt
  }

  // =========================================================================
  // Test 6.3: "Better than the reference scanner" — canonical pURL uses POM groupId
  // =========================================================================
  //
  // What it tests:
  //   For corpus JARs with companion POMs, Goat Rodeo's canonical pURL
  //   uses the companion POM's groupId — NOT the filename. This
  //   demonstrates Goat Rodeo is "better than the reference scanner" because the reference scanner often
  //   uses the filename/pathname as the groupId (a known reference scanner failure).
  //
  // Why it's relevant:
  //   REQ-6 — "Goat Rodeo pURLs must either match what the reference scanner finds or be
  //   better than what the reference scanner finds. The reference scanner will often use the filename/pathname
  //   as the groupId and artifactId — this is a failure on the reference scanner's part."
  //
  // Requirement section:
  //   REQ-6.
  //
  // Theory:
  //   For each corpus JAR with a companion POM:
  //   1. Parse the companion POM to get expected groupId.
  //   2. Process the JAR through the full pipeline.
  //   3. Extract the canonical pURL.
  //   4. Assert the canonical pURL's groupId matches the POM's groupId.
  //   5. Assert the canonical pURL's groupId is NOT the filename (which
  //      is what the reference scanner would use if it fell back to filename-derived pURL).

  /** Maven Central-verified coordinates for Test 6.3 and 6.4.
    *
    * Each entry is (jarPath, groupId, artifactId, version). All coordinates
    * were manually verified to exist in Maven Central at
    * https://repo1.maven.org/maven2/ on 2026-07-08.
    */
  private val mavenCentralVerified: Vector[(String, String, String, String)] =
    Vector(
      (
        "test_data/download/adg_tests/repo_ea/AddOnJavaAntTasks-2.11.jar",
        "uk.co.firstzero",
        "AddOnJavaAntTasks",
        "2.11"
      ),
      (
        "test_data/download/adg_tests/repo_ea/AddRemoveComboBox-0.5.jar",
        "tech.ugma.customcomponents",
        "AddRemoveComboBox",
        "0.5"
      ),
      (
        "test_data/download/adg_tests/repo_ea/Agrona-0.1.jar",
        "uk.co.real-logic",
        "Agrona",
        "0.1"
      ),
      (
        "test_data/download/adg_tests/repo_ea/Allen4J-1.0.1.jar",
        "xyz.lamergameryt",
        "Allen4J",
        "1.0.1"
      ),
      (
        "test_data/download/adg_tests/repo_ea/AnnotationSummariser-1.2.0.jar",
        "uk.ac.mmu.tdmlab.uima",
        "AnnotationSummariser",
        "1.2.0"
      ),
      (
        "test_data/download/adg_tests/repo_ea/ArgoWirelineFormat-0.3.1.jar",
        "ws.argo.wireline",
        "ArgoWirelineFormat",
        "0.3.1"
      ),
      (
        "test_data/download/adg_tests/repo_ea/abris-0.0.1.jar",
        "za.co.absa",
        "abris",
        "0.0.1"
      ),
      (
        "test_data/download/adg_tests/repo_ea/absa-shaded-jackson-0.0.1.jar",
        "za.co.absa.shaded",
        "absa-shaded-jackson",
        "0.0.1"
      ),
      (
        "test_data/download/adg_tests/repo_ea/abstraction-models-1.0.48.jar",
        "tech.rsqn.useful-things",
        "abstraction-models",
        "1.0.48"
      ),
      (
        "test_data/download/adg_tests/repo_ea/ac-client-2.0.0.jar",
        "tech.figure.classification.asset",
        "ac-client",
        "2.0.0"
      ),
      (
        "test_data/download/adg_tests/repo_ea/access-system-0.0.14.jar",
        "tz.co.asoft",
        "access-system",
        "0.0.14"
      ),
      (
        "test_data/download/adg_tests/repo_ea/acpgeo-0.0.2.jar",
        "uk.ac.cam.ch.wwmm",
        "acpgeo",
        "0.0.2"
      )
    )

  mavenCentralVerified.foreach {
    case (jarPath, expectedG, expectedA, expectedV) =>
      val jarFile = new File(jarPath)
      val testName = jarFile.getName

      test(
        s"Test 6.3: $testName — canonical pURL groupId from POM (not filename)"
      ) {
        assume(jarFile.exists(), s"JAR not found: $jarPath")

        val store = processCorpusJar(jarFile)
        val canonicalPurlOpt = extractCanonicalPurl(store, jarFile)

        assert(
          canonicalPurlOpt.isDefined,
          s"Canonical pURL should be present.\nJAR: $jarPath"
        )

        val canonicalPurl = canonicalPurlOpt.get

        // Structured check: parse the pURL and compare groupId directly.
        // This replaces fragile substring checks (`.contains(s"$expectedG/")`)
        // with robust structured parsing.
        val purlParts = PurlParts.parse(canonicalPurl)
        assert(
          purlParts.isDefined,
          s"Failed to parse canonical pURL: $canonicalPurl"
        )

        purlParts.foreach { parts =>
          assert(
            parts.groupId == expectedG,
            s"""Canonical pURL groupId should be from companion POM, not filename.
             |
             |Expected (from POM): $expectedG
             |Actual (from pURL):  ${parts.groupId}
             |Canonical pURL: $canonicalPurl
             |Filename-derived groupId would be: ${filenameArtifactId(testName)}
             |JAR: $jarPath
             |""".stripMargin
          )

          // The canonical pURL must NOT use the filename as groupId
          // (when they differ — if they're the same, the check is trivially true).
          val fnameArt = filenameArtifactId(testName)
          if (expectedG != fnameArt) {
            assert(
              parts.groupId != fnameArt,
              s"""Canonical pURL should NOT use filename as groupId.
               |
               |Filename-derived groupId: $fnameArt
               |POM groupId: $expectedG
               |Actual groupId: ${parts.groupId}
               |Canonical pURL: $canonicalPurl
               |JAR: $jarPath
               |""".stripMargin
            )
          }
        }

        // Compare against reference metadata ground truth.
        // This verifies Goat Rodeo is "better than" the reference scanner:
        // when the scanner uses a filename-derived groupId (wrong), Goat
        // Rodeo uses the POM's groupId (correct).
        MetadataGroundTruth.findEntry(regularJarMetadata, testName).foreach {
          entry =>
            entry.purls.headOption.foreach { scannerPurl =>
              val scannerParts = PurlParts.parse(scannerPurl)
              scannerParts.foreach { scanner =>
                // Goat Rodeo's groupId should match the POM's groupId
                // (already asserted above). If the scanner's groupId differs,
                // that demonstrates Goat Rodeo is more accurate.
                if (scanner.groupId != expectedG) {
                  // The scanner used a different (likely filename-derived) groupId.
                  // Goat Rodeo uses the correct one from the POM.
                  assert(
                    purlParts.exists(_.groupId == expectedG),
                    s"""Goat Rodeo should use POM groupId '$expectedG', not scanner's '${scanner.groupId}'.
                   |
                   |Scanner pURL: $scannerPurl (groupId: ${scanner.groupId})
                   |Goat Rodeo pURL: $canonicalPurl
                   |POM groupId: $expectedG
                   |JAR: $jarPath
                   |""".stripMargin
                  )
                }
              }
            }
        }
      }
  }

  // =========================================================================
  // Test 6.4: Maven Central validation — canonical pURLs match Maven Central
  // =========================================================================
  //
  // What it tests:
  //   For 12 corpus JARs with companion POMs, the canonical pURL matches
  //   hardcoded Maven Central coordinates (manually verified to exist).
  //
  // Why it's relevant:
  //   REQ-3 — "The test for whether the correct groupId/artifactId/version
  //   was chosen is: can the artifact be found in Maven Central with the
  //   exact groupId/artifactId/version derived and is it the same artifact?"
  //
  // Requirement section:
  //   REQ-3, Maven Central validation.
  //
  // Theory:
  //   For each JAR:
  //   1. Process through the full Maven pipeline (directory-based, with POM).
  //   2. Extract the canonical pURL.
  //   3. Assert it equals pkg:maven/<g>/<a>@<v> where g/a/v are the
  //      Maven Central-verified coordinates.

  mavenCentralVerified.foreach {
    case (jarPath, expectedG, expectedA, expectedV) =>
      val jarFile = new File(jarPath)
      val testName = jarFile.getName
      val expectedPurl = s"pkg:maven/$expectedG/$expectedA@$expectedV"

      test(s"Test 6.4: $testName — canonical pURL matches Maven Central") {
        assume(jarFile.exists(), s"JAR not found: $jarPath")

        val store = processCorpusJar(jarFile)
        val canonicalPurlOpt = extractCanonicalPurl(store, jarFile)

        assert(
          canonicalPurlOpt.isDefined,
          s"Canonical pURL should be present.\nJAR: $jarPath"
        )

        val canonicalPurl = canonicalPurlOpt.get

        // Strip any query qualifier (e.g., ?type=jar) for comparison
        val basePurl = PurlParts.normalize(canonicalPurl)

        assertEquals(
          basePurl,
          expectedPurl,
          s"""Canonical pURL must match Maven Central coordinate.
           |
           |Expected (Maven Central): $expectedPurl
           |Actual (Goat Rodeo):     $canonicalPurl
           |JAR: $jarPath
           |""".stripMargin
        )
      }
  }

  // =========================================================================
  // Test 6.6: Companion POM priority in full pipeline
  // =========================================================================
  //
  // What it tests:
  //   For corpus JARs with companion POMs AND embedded pom.properties,
  //   the canonical pURL comes from the companion POM (highest priority),
  //   NOT from pom.properties or manifest.
  //
  // Why it's relevant:
  //   BestPurlSuite (Test 6.2) calls resolveGroupIdArtifactIdVersion
  //   directly with externalPom=None. This test verifies the FULL pipeline
  //   with companion POM produces the correct canonical pURL — specifically
  //   that the POM wins over pom.properties and manifest.
  //
  // Requirement section:
  //   REQ-3 + REQ-8.
  //
  // Theory:
  //   For each corpus JAR with a companion POM:
  //   1. Parse the companion POM to get expected g/a/v.
  //   2. Process through the full pipeline (directory-based, with POM).
  //   3. Extract the canonical pURL.
  //   4. Assert it matches the POM's g/a/v (not pom.properties or manifest).

  // Use the same 12 Maven Central-verified JARs
  mavenCentralVerified.foreach {
    case (jarPath, expectedG, expectedA, expectedV) =>
      val jarFile = new File(jarPath)
      val testName = jarFile.getName
      val pomFile = companionPom(jarFile)

      test(
        s"Test 6.6: $testName — canonical pURL from companion POM in pipeline"
      ) {
        assume(jarFile.exists(), s"JAR not found: $jarPath")
        assume(pomFile.isDefined, s"Companion POM not found for: $jarPath")

        // Parse the companion POM to get expected coordinates
        val parsedPom = parseCompanionPom(pomFile.get)
        assert(
          parsedPom.isDefined,
          s"Failed to parse companion POM: ${pomFile.get}"
        )

        val pomG = parsedPom.get.groupId.orElse(parsedPom.get.parentGroupId)
        val pomA = parsedPom.get.artifactId
        val pomV = parsedPom.get.version.orElse(parsedPom.get.parentVersion)

        assert(pomG.isDefined, s"POM groupId not found: ${pomFile.get}")
        assert(pomA.isDefined, s"POM artifactId not found: ${pomFile.get}")
        assert(pomV.isDefined, s"POM version not found: ${pomFile.get}")

        val expectedPurl = s"pkg:maven/${pomG.get}/${pomA.get}@${pomV.get}"

        val store = processCorpusJar(jarFile)
        val canonicalPurlOpt = extractCanonicalPurl(store, jarFile)

        assert(
          canonicalPurlOpt.isDefined,
          s"Canonical pURL should be present.\nJAR: $jarPath"
        )

        val canonicalPurl = canonicalPurlOpt.get

        // Strip any query qualifier for comparison
        val basePurl = PurlParts.normalize(canonicalPurl)

        assertEquals(
          basePurl,
          expectedPurl,
          s"""Canonical pURL should come from companion POM (highest priority).
           |
           |Expected (from POM): $expectedPurl
           |Actual (Goat Rodeo): $canonicalPurl
           |POM file: ${pomFile.get.getAbsolutePath}
           |JAR: $jarPath
           |""".stripMargin
        )
      }
  }

  // =========================================================================
  // Test 6.5: pURL count >= reference scanner pURL count (explicit, sampled)
  // =========================================================================
  //
  // What it tests:
  //   For a sample of JARs from the MultiplePurlSuite data, Goat Rodeo
  //   finds at least as many pURLs as the reference scanner. This is an explicit count
  //   check — MultiplePurlSuite checks superset (which implies count >=),
  //   but this test makes the count assertion explicit.
  //
  // Why it's relevant:
  //   REQ-6 — "Goat Rodeo must find at least as many pURLs as the reference scanner for
  //   each JAR."
  //
  // Requirement section:
  //   REQ-6.
  //
  // Theory:
  //   For 10 sampled JARs from the MultiplePurlSuite data:
  //   1. Process through the full pipeline (with companion POM).
  //   2. Count Goat Rodeo's alias:from pURLs.
  //   3. Count the reference scanner's pURLs (from metadata_multiple_purls.json).
  //   4. Assert Goat Rodeo count >= reference scanner count (after normalizing classifiers).

  private val referenceEntries = MultiplePurlSuite.referenceEntries
    .filter { entry =>
      val jarFile = new File(entry.path)
      jarFile.exists() &&
      MultiplePurlSuite.hasCompanionPom(jarFile) &&
      !MultiplePurlSuite.hasNestedJars(jarFile)
    }

  // Sample 10 JARs deterministically
  private val sampledReferenceEntries = {
    if (referenceEntries.isEmpty) Vector.empty
    else {
      val step = math.max(1, referenceEntries.length / 10)
      referenceEntries.indices
        .filter(_ % step == 0)
        .map(referenceEntries(_))
        .toVector
    }
  }

  // Sentinel test: ensure metadata entries are loaded and sampled.
  // Without this, if the JSON resource is missing or all entries are
  // filtered out, zero tests are generated for Test 6.5 — which looks
  // like success but tests nothing.
  test("Test 6.5 sentinel: metadata entries are non-empty") {
    assert(
      referenceEntries.nonEmpty,
      "Metadata entries from metadata_multiple_purls.json should not be empty. " +
        "If this fails, the JSON resource may be missing or corrupt."
    )
    assert(
      sampledReferenceEntries.nonEmpty,
      "Sampled metadata entries should not be empty. " +
        "If this fails, all entries may have been filtered out (missing JARs, nested JARs, etc.)."
    )
  }

  sampledReferenceEntries.foreach { entry =>
    test(
      s"Test 6.5: ${entry.name} — pURL count >= reference (${entry.purls.size} reference pURLs)"
    ) {
      MavenTestHelpers.withTempDir(s"phase6-count-${entry.name}") { dir =>
        val jarFile = new File(entry.path)
        val pomFile = MultiplePurlSuite.companionPom(jarFile).get
        val destJar = new File(dir, jarFile.getName)
        val destPom = new File(dir, pomFile.getName)
        Files.copy(jarFile.toPath, destJar.toPath)
        Files.copy(pomFile.toPath, destPom.toPath)

        val store = MavenTestHelpers.processDirectoryWithStore(dir)
        val goatPurls = extractGoatRodeoPurls(store, destJar)

        // Normalize: strip classifiers for comparison
        val normalizedGoat = goatPurls.map(PurlParts.normalize)
        val normalizedReference = entry.purls.toSet.map(PurlParts.normalize)

        assert(
          normalizedGoat.size >= normalizedReference.size,
          s"""Goat Rodeo found ${normalizedGoat.size} pURLs but the reference scanner found ${normalizedReference.size}.
             |
             |Goat Rodeo pURLs (${goatPurls.size} raw, ${normalizedGoat.size} normalized):
             |  ${normalizedGoat.toList.sorted.mkString("\n  ")}
             |
             |Reference scanner pURLs (${entry.purls.size} raw, ${normalizedReference.size} normalized):
             |  ${normalizedReference.toList.sorted.mkString("\n  ")}
             |
             |JAR: ${entry.path}
             |""".stripMargin
        )
      }
    }
  }
}
