name: Build ADG from JAR

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-hotspot'
        cache: 'sbt'

    - name: Set up sbt
      uses: sbt/setup-sbt@v1

    - name: Build Goat Rodeo Package
      run: sbt package

    - name: Set up directories for running Goat Rodeo against the Goat Rodeo package
      run: |
        mkdir -p target/input
        mkdir -p target/output
        cp target/scala-*/goatrodeo*.jar target/input

    - name: Run Goat Rodeo against the Goat Rodeo package
      run: |
        docker run --platform linux/amd64 --quiet --rm --network none \
           --user $(id -u):$(id -g) \
           -v $(pwd)/target/input:/input:ro \
           -v $(pwd)/target/output:/output \
           spicelabs/goatrodeo:0.6.3 \
           -b /input \
           -o /output

    - name: Upload with Ginger
      run: |
        docker run -ti --rm -v $(pwd)/target/output:/data/to_upload ghcr.io/spice-labs-inc/ginger:0.1.10 -j ${{ secrets.GRINDER_JWT }} -p /data/to_upload -m bt
