# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala Build & Test

on:
  push:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout with LFS
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'sbt'
    - name: Set up sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: SBT_OPTS="-Xmx8G  -Duser.timezone=GMT" TEST_THREAD_CNT="2" sbt test
      # Optional: This step uploads information to the GitHub dependency graph and unblocking Dependabot alerts for the repository
    #- name: Upload dependency graph
    # uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
