name: Publish Binaries

on:
  workflow_run:
    workflows: ["Publish Scala Container Images"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to run the workflow on"
        required: true
        default: "main"

jobs:
  publish_binaries:
    name: Publish Compiled JAR Files
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt-hotspot'
          cache: 'sbt'

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Build and Package with SBT
        run: |
          sbt compile
          sbt package

      - name: Publish Binaries to GitHub Releases
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          args: target/scala-*/goatrodeo*.jar
